### ISSUE TITLE
Suggestion for dependency injection

### ISSUE THREAD

**Issue by richardsorensson** [fluentscheduler/FluentScheduler#100]
Hi,

Thought about some minor feedback regarding DI, instead of doing this on the fly to a static JobManager.

JobManager.JobFactory = new StructureMapJobFactory();
JobManager.Initialize(new MyRegistry()); 

Couldn't the dependency injector handle how the JobManager is instanced and from a ctor one would then just have a param of IJobManager.

I've also got a suggestion for the .Start() and .Stop(), as of now it seems as Start() is actually triggered when you call Initialize(). I'd be good if start wasn't triggered in initialize when doing DI as there might be cases where you explicitly want to start it at a certain time other then when creating the instance.

An idea could be to add a "autoStart = true" default parameter for backward compatibility.

Hope any ideas could be of interest.

**Comment by tallesl** [comment]
Hi there,

There's basically two ways to design an API. One is the opinative way, where the API demands interfaces to be implemented and very specific calls for initialization and such. The other is focusing on doing only its job and messing as little as possible with the application design.

The former is what we refer as 'framework' while the latter is what 'library' was supposed to be.

I'm pointing FluentScheduler in the opposite direction of what you pictured. While frameworks aren't inherently bad in my book, I found libraries to be much more useful overall. I'm planning to [simplify even further the API](https://github.com/fluentscheduler/FluentScheduler/issues/71). As for the DI part, I think [hooking up just an Action](https://github.com/fluentscheduler/FluentScheduler/issues/71#issuecomment-222533918) would be the best overall.

I'm closing the issue but feel free to comment further on it.

**Comment by richardsorensson** [comment]
What i think it boils down to, with or without an interface for JobManager is that the method intialize() or future versions of the framework doesn't auto start all jobs until start() has been called.

e.g. when registering everything through a di container today it'd force the jobs to start running right away when initializing the registry.

Thanks.

**Comment by tallesl** [comment]
> when registering everything through a di container today it'd force the jobs to start running right away when initializing the registry.

Huh?
