### ISSUE TITLE
Support  custom parameters

### ISSUE THREAD

**Issue by AlonAm** [fluentscheduler/FluentScheduler#101]
Would be useful to be able to add parameters to a job AND use IoC
For example:

JobManager.AddJob(s => s.WithParameter("Param1", myParam).ToRunOnceAt(date));

**Comment by tallesl** [comment]
How the job would access what was set on `s.WithParameter("Param1", myParam)`? A dictionary handled by the library?

That doesn't sound really good...

**Comment by tallesl** [comment]
I'm closing the issue but feel free to comment further on it.
