### ISSUE TITLE
Add logging.

### ISSUE THREAD

**Issue by skorunka** [fluentscheduler/FluentScheduler#102]
Add logging to `try{} finally{}` blocks.

        internal static Action GetJobAction<T>() where T : IJob
        {
            return () =>
            {
                var job = JobFactory.GetJobInstance<T>();
                try
                {
                    job.Execute();
                }
                finally
                {
                    DisposeIfNeeded(job);
                }
            };
        }

I had to download source code and reference project to be able to debug code and find out that I forgot to setup container to include a my IJob implementations.

**Comment by tallesl** [comment]
What error did you get when you forgot to setup your container?

**Comment by skorunka** [comment]
I did not get any error, as the exception is suppressed (see the code above). So, actually the job was not executed.

**Comment by tallesl** [comment]
The exception is not suppressed by the code you posted (there's no `catch` block). You can check what happened at runtime with the `JobManager.JobException` event, like:

```cs
JobManager.JobException += (JobExceptionInfo info) => Console.WriteLine(info.Exception);
``` 

I'm pretty sure that the exception raised by your job factory implementation will show there.

I'm closing this issue but feel free to comment further on it.
