### ISSUE TITLE
FluentScheduler  启动任务，怎么找到对应的线程

### ISSUE THREAD

**Issue by wangli19** [fluentscheduler/FluentScheduler#103]
FluentScheduler  启动任务，怎么找到对应的线程

**Comment by tallesl** [comment]
Hi,

I don't speak Chinese so to Google Translate I went:

> Start the task, how to find the corresponding thread

Well, if by the translated *thread* you mean the actual thread, you can't. The library uses [Task](https://msdn.microsoft.com/library/System.Threading.Tasks.Task) under the hood and you don't have an access to it.

But if you want to access the schedule instance, you can search for it on `JobManager.RunningSchedules` or `JobManager.AllSchedules`.
