### ISSUE TITLE
Please help me answer， I plan to doubt

### ISSUE THREAD

**Issue by wangli19** [fluentscheduler/FluentScheduler#106]
Register in Application_Start  

![image](https://cloud.githubusercontent.com/assets/22094293/18695828/00e8fe14-7fe7-11e6-9fcf-b168213521de.png)

          foreach (var itemtiming in strTiming.Split(','))
                            {
                                var arr = itemtiming.Split(':');
                                int hour = Int32.Parse(arr[0]);
                                int minutes = Int32.Parse(arr[1]);
                                TimingPlan(info, type, instance, strKey, hour, minutes);
                            }

public void TimingPlan(MemberInfo info, Type type, object instance, string strKey, int hour, int minutes)
        {
            Schedule(() =>
            {
                LogHelper.WriteLog("缓存定时执行", "【" + strKey + "】开始执行");
                try
                {
                    var method = type.GetMethod(info.Name, new Type[] { });
                    object obj = method.Invoke(instance, null);
                    var jsonStr = JsonConvert.SerializeObject(obj, new IsoDateTimeConverter { DateTimeFormat = "yyyy/MM/dd" });
                    if (RedisHelper.Item_Set<string>(strKey, jsonStr))
                    {
                        LogHelper.WriteLog("缓存定时执行", "【" + strKey + "】执行完成");
                    }
                    else
                    {
                        LogHelper.WriteLog("缓存定时执行", "【" + strKey + "】执行失败");
                    }
                }
                catch (Exception e)
                {
                    LogHelper.WriteLog("缓存定时执行", "【" + strKey + "】执行异常：" + e.Message + "\r\n" + e.StackTrace + "\r\n");
                }
            }).WithName("RedisCache").ToRunEvery(1).Days().At(hour, minutes);
        }

1.请问程序启动了之后，计划任务会每天的多个时间都会执行吗
1 after the program is started, the planning task will be executed every day, more than a day

2

**Comment by wangli19** [comment]
@tallesl Please help me to answer, thank you！

**Comment by tallesl** [comment]
Hi @wangli19 

I'm afraid that I'm unable to grasp what you mean... sorry!
