### ISSUE TITLE
Docs - teardown/shutdown

### ISSUE THREAD

**Issue by Paradroid888** [fluentscheduler/FluentScheduler#109]
I'm using FluentScheduler inside a Topshelf Windows Service. Is it correct to call JobManager.Stop in the Stop event of the service, or is this unnecessary?

I'm thinking about teardown and how it interacts with Windows Service control. Can FluentScheduler block a service shutdown until the current task has completed, and shut down cleanly?

Thanks for a great library.

**Comment by tallesl** [comment]
First off, sorry for taking so long to respond.

Calling just `Stop` wouldn't be right, `Stop` just stops the timer but it doesn't block until the currently running jobs ends.

I'm working on a `StopAndBlock` implementation (#93), it won't take long until I publish it.
As soon I get it done I let you know here and document it on README.

**Comment by Paradroid888** [comment]
Awesome, many thanks 👍
