### ISSUE TITLE
Release/dispose for IJobFactory

### ISSUE THREAD

**Issue by mbp** [fluentscheduler/FluentScheduler#110]
So in order to get dependency injection in jobs, we implement `GetJobInstance` in `IJobFactory`.

However, when the job is done, there might be resources that are supposed to be released/disposed..

Suggestion: Add a Release method to IJobFactory and call it when a job is done.

**Comment by mdissel** [comment]
I think implementing IDisposable is enough.

**Comment by tallesl** [comment]
As @mdissel said, it's just a matter of implementing `IDisposable` on your `IJob` and [the library will dispose your job after it's done with it](https://github.com/fluentscheduler/FluentScheduler/blob/32307bdee4a6ef2d80568b4c499a6514959b80f4/Library/JobManager.cs#L93-L99).

**Comment by mbp** [comment]
Actually no, that won't do. You ara referring to `IDisposable` on `IJob` which I can see a (different) purpose for.

What I mean is a way to properly tell the dependency injection framework, that a previously created instance using `IJobFactory` is now completed and can be removed from memory, along with all the dependencies it took. Or else we will get leaks in the application if the instances are transient.

Exactly how in MVC we implement `DefaultControllerFactory` which has a `ReleaseController` method, an example can be seen here: http://stackoverflow.com/a/30261663

**Comment by tallesl** [comment]
An `IJob` is instantiated by the library when the time to run it arrives and is released (and disposed if that's the case) when the library is done with running the job. The library knows both when the job starts to live and when it ends, it has full control over it's lifetime.

Now, as for the `IJobFactory`, the library only uses what you set, it does nothing else besides calling `GetJobInstance` on it. In other words, it doesn't mess with its lifetime, instantiating/freeing/changing the instance is entirely on your shoulders.

**Comment by mdissel** [comment]
Correct, see #111

**Comment by mbp** [comment]
@tallesl I can't see how I can take it on my shoulders to release the instance. Only FluentScheduler knows when the job is done.

Consider the following example:

    public class JobRegistry : Registry
    {
        public JobRegistry()
        {
            Schedule<Job>().ToRunEvery(2).Seconds();
        }
    }

    public class JobFactory : IJobFactory
    {
        public IJob GetJobInstance<T>() where T : IJob
        {
            // Use favourite dependency injection framework here, but basically it will do this:
            return new Job(new ObtainResource());
        }
    }

    public class Job : IJob
    {
        public Job(IObtainResource obtainResource)
        {
        }

        public void Execute()
        {
        }
    }

    public interface IObtainResource
    {
    }

    public class ObtainResource : IObtainResource, IDisposable
    {
        private static bool  _isLocked = false;

        public ObtainResource()
        {
            if (_isLocked)
            {
                throw new InvalidOperationException("Cannot open file which is locked!");
            }
            // "Lock" a resource. It might be a file, database connection, or anything.
            _isLocked = true;
        }

        public void Dispose()
        {
            // Release the resource
            _isLocked = true;
        }
    }

What I would expect is that JobFactory have a method `ReleaseJobInstance` which is called after the Job is done executing.

**Comment by tallesl** [comment]
> Only FluentScheduler knows when the job is done.

`IJob` != `IJobFactory`.

For `IJob`, FluentScheduler instantiates it and disposes if it's an `IDisposable`.
As for `IJobFactory`, *you* instantiate it and *you* set it in the library, the library does nothing besides just using it.

In your example, change `IJob` to implement `IDisposable` (and not `IJobFactory`).
