### ISSUE TITLE
Initiate new instance of job when executing not when scheduling

### ISSUE THREAD

**Issue by mdissel** [fluentscheduler/FluentScheduler#111]
Currently the GetJobInstance<T> is called when the job is scheduled. https://github.com/fluentscheduler/FluentScheduler/blob/32307bdee4a6ef2d80568b4c499a6514959b80f4/Library/JobManager.cs#L282

I opt for creating the instance of the job when executed..

Slightly related to #110

**Comment by mbp** [comment]
@mdissel as I read the code, the creation of the instance is actually done when executing, not when scheduled.

The function you link to, calls `GetJobAction` and only gets an Action to execute later, and not the actual `IJob` instance.

The action is invoked here: https://github.com/fluentscheduler/FluentScheduler/blob/32307bdee4a6ef2d80568b4c499a6514959b80f4/Library/JobManager.cs#L441

**Comment by mdissel** [comment]
Oeps.. I missed the delegated action..

**Comment by mdissel** [comment]
But on this line the job is also created (and not disposed if it implements IDisposable 
https://github.com/fluentscheduler/FluentScheduler/blob/32307bdee4a6ef2d80568b4c499a6514959b80f4/Library/JobManager.cs#L282

**Comment by mbp** [comment]
Are you sure that link is correct? Don't see any job being created there.

**Comment by tallesl** [comment]
The [GetJobAction](https://github.com/fluentscheduler/FluentScheduler/blob/32307bdee4a6ef2d80568b4c499a6514959b80f4/Library/JobManager.cs#L62-L76) call only constructs an action that will then call the job factory, but the action is only constructed immediately (and not called).

You can test for yourself:

```cs
using FluentScheduler;
using System;
using System.Threading;

public class Job : IJob, IDisposable
{
    public Job()
    {
        Console.WriteLine("{0} Constructor called.", DateTime.Now);
    }

    public void Execute()
    {
        Console.WriteLine("{0} Execute called.", DateTime.Now);
    }

    public void Dispose()
    {
        Console.WriteLine("{0} Dispose called.", DateTime.Now);
    }
}

public class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("{0} Application started.", DateTime.Now);

        var registry = new Registry();
        registry.Schedule<Job>().ToRunEvery(5).Seconds();
        Console.WriteLine("{0} Registry setup.", DateTime.Now);

        JobManager.Initialize(registry);
        Console.WriteLine("{0} Job manager initialized.", DateTime.Now);

        Thread.Sleep(Timeout.Infinite);
    }
}
```


Output:

```
11/10/2016 17:59:31 Application started.
11/10/2016 17:59:31 Registry setup.
11/10/2016 17:59:31 Job manager initialized.
11/10/2016 17:59:41 Constructor called.
11/10/2016 17:59:41 Execute called.
11/10/2016 17:59:41 Dispose called.
11/10/2016 17:59:51 Constructor called.
11/10/2016 17:59:51 Execute called.
11/10/2016 17:59:51 Dispose called.
```
