### ISSUE TITLE
schedule jobs on multiple fixed times on a day

### ISSUE THREAD

**Issue by mdissel** [fluentscheduler/FluentScheduler#114]
Can we schedule a job to run on (for example):
01:00
06:00
13:00
17:00
21:00

**Comment by tallesl** [comment]
You can, but you have to make separate schedules.

```cs
Schedule<MyJob>().ToRunOnceAt(1, 0);
Schedule<MyJob>().ToRunOnceAt(6, 0);
Schedule<MyJob>().ToRunOnceAt(13, 0);
Schedule<MyJob>().ToRunOnceAt(17, 0);
Schedule<MyJob>().ToRunOnceAt(21, 0);
```

**Comment by mdissel** [comment]
That is a partial solution. In my case the jobs should be non-reantrant and that will not work with separate jobs/scheduling.
