### ISSUE TITLE
Schedule job stops running after few hours

### ISSUE THREAD

**Issue by chukkalasandeep** [fluentscheduler/FluentScheduler#116]
Hi,

I have created a sample job to create entries when ever the job is running I insert a record into the database. Below is the code for the job and the registry class.
```
public class ScheduledJobsRegistry : Registry
{
        private DbContextClass db = new DbContextClass();

        public ScheduledJobsRegistry() 
        {
            Schedule(() => TestJob()).ToRunNow().AndEvery(1).Hours();
        }

        public void TestJob()
        {
            db.HttpPostLogs.Add(new HttpPostLog { MESSAGES = "Job called at" + DateTime.Now });
            db.SaveChanges();
        }
}
```
And in Global.asax 

```
protected void Application_Start()
        {
            JobManager.Initialize(new ScheduledJobsRegistry());
        }
```
So I publish my project to test the scheduler, when I initially run the project the record is inserted into the Db but after few hours the there are no records inserted.

Do you know why?

**Comment by mdissel** [comment]
You have to disable the recycling of the apppool in IIS or else the process will be stopped after no (http) activitity.

**Comment by chukkalasandeep** [comment]
If we disable the recycling of the apppool will there be memory stacking issue for the application?

**Comment by tallesl** [comment]
Are you using it with a ASP.NET application? Did you registered the job on the hosting environment?

[Using it with ASP.NET](https://github.com/fluentscheduler/FluentScheduler#using-it-with-aspnet)

**Comment by chukkalasandeep** [comment]
I am using the Job as an action, so I created the registry class with the job action and in the application start method I am initializing the job manager with the registry class.
Do I still need to register the job on the the hosting environment? Also I am using Amazon web services to host my application, so please guide me how to implement the scheduler to run continuously.

**Comment by tallesl** [comment]
Are you using it with an ASP.NET application or not? If you are, yes, you do have to register.

Here's an article that might help: [The Dangers of Implementing Recurring Background Tasks In ASP.NET](http://haacked.com/archive/2011/10/16/the-dangers-of-implementing-recurring-background-tasks-in-asp-net.aspx/).

I'm closing this issue but feel free to comment further on it.

**Comment by chukkalasandeep** [comment]
I have registered the job to the Hosting Environment, but still the job is running only when there is http activity, if there is not http activity the job is stopping. Any work around for this?

**Comment by tallesl** [comment]
You mentioned you're using Amazon Web Services. Maybe it's the same problem with Azure... (#80)

**Comment by mdawood1991** [comment]
Hi @tallesl ,

I am running this in a windows service, and I am facing the same problem. The Schedule stops running after a couple of hours.

In the OnStart function of the windows service I am starting the JobManager

```
public void Start()
{
    try
    {
        // Setup the Fluent Scheduler -
        JobManager.UseUtcTime();
        JobManager.Start();

    }
    catch (Exception ex)
    {
        _logger.LogExceptionMessage(ex.Message, ex.InnerException, ex.StackTrace);
    }
}
```

This is how I am creating the Jobs - 

```
//create report Job
var reportJob = new ReportJob();
						
Action<Schedule> schedule = s => s.WithName(subscription.SubscriptionId.ToString()).ToRunEvery(subscription.Scheduler.Interval).Hours().At(0);
JobManager.AddJob(reportJob, schedule)
```
