### ISSUE TITLE
Dot net publish on .net core version FluentScheduler "5.1.0" does not include the run time dlls

### ISSUE THREAD

**Issue by jayalakshmis** [fluentscheduler/FluentScheduler#118]
**Issue:** When I run `dotnet publish` against my project , the platform specific runtime dlls are not included. Is there a specific run time that should be used? 

My .NET Core console app that uses FluentScheduler 5.1.0 has a project.json that looks like:

```{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "warningsAsErrors": true,
    "copyToOutput": {
      "include": [
        "appsettings*.json",
        "App*.config"
      ]
    }
  },
  "dependencies": {
     "FluentScheduler": "5.0.0",
    "Microsoft.Extensions.Configuration": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Options": "1.0.0",
    "Microsoft.NETCore.App": {
      "type": "build",
      "version": "1.0.1"
    },
    "Newtonsoft.Json": "9.0.1",
   
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },
  "runtimes": {
    "win7-x64": {}
  },
  "publishOptions": {
    "include": [
      "appsettings.json",
      "appsettings.*.json",
      "settings.job",
      "run.cmd",
      
    ]
  }
}
```

**Notes**
A sample of a run time dll generated when using other libraries with win7-x64 is  `api-ms-win-core-datetime-l1-1-0.dll`.

**Comment by tallesl** [comment]
It's been awhile since I last used .NET Core, I'll try to find out what's going with this issue in the future.
In the meanwhile, I added a "help wanted" label to this issue and a remark on README inviting others to help.

**Comment by tallesl** [comment]
There are issues on using the current version of the library with .NET Core (#118, #159, #208).

I think those came from the current support being a portable library thingy, made prior to core 2.0, and poorly tested by me (sorry).

I'm relunctant on making changes on the current version that lives on master, however the current library redesign (#214) is been done entirely in .NET Core.

I kindly ask you folks to wait for the redesign to be done.
