### ISSUE TITLE
Support for the TimeSpan datatype

### ISSUE THREAD

**Issue by FSMaxB** [fluentscheduler/FluentScheduler#119]
It would be nice if you could add the possibility to schedule jobs to run every `TimeSpan` using `System.TimeSpan`.

For example `.ToRunEvery(timespan)`

**Comment by FSMaxB** [comment]
My current workaround:

```c#
using System;

namespace FluentScheduler.Extensions
{
    public static class FluentSchedulerExtensions
    {
        ///Schedule a FluentScheduler Job using TimeSpan
        public static SecondUnit ToRunEvery(this Schedule schedule, TimeSpan timespan)
        {
            var seconds = (int)Math.Ceiling(Math.Abs(timespan.TotalSeconds));
            seconds = seconds == 0 ? 1 : seconds;
            return schedule.ToRunEvery((int)timespan.TotalSeconds).Seconds();
        }
    }
}
```

**Comment by tallesl** [comment]
Yeah, I feel you, I had to do something similar one time.

**Comment by puf17640** [comment]
Has this already been implemented? I know it's been nearly 2 years, but I'd be interested to help!

**Comment by VitorCioletti** [comment]
@puf17640  We did not implement that yet, however, I believe it would be a fine overload to implement in the new version of the library.

See #214
