### ISSUE TITLE
Some sort of admin user interface?

### ISSUE THREAD

**Issue by ChangePlaces** [fluentscheduler/FluentScheduler#121]
A simple admin user interface would be helpful. Something to view scheduled jobs, possibly edit / delete / add new jobs.

If not, a REST api would be handy.

**Comment by tallesl** [comment]
FluentScheduler is supposed to be a lightweight and quick to use scheduler, I don't think it would be a good idea bundling it with such interface or even a fully fledged REST API.

If someone decided to implement it and keep as a separate package that would be cool though.
