### ISSUE TITLE
Grouping schedules and grouping jobs

### ISSUE THREAD

**Issue by ChangePlaces** [fluentscheduler/FluentScheduler#122]
It'd be nice to be able to run / pause all schedules that belong to a group. It'd also be nice to be able to pause / resume all jobs that belong to a group that's independent of the scheduler group.

E.g. 
- pause all jobs that belong to the "ReportGenerators" group.
- pause all schedules that belong to the "AccountsDept" group

**Comment by tallesl** [comment]
Hmm... that's a good idea.

I'll let it hang here with a new feature label, hopefully implementing it in the future.

**Comment by tallesl** [comment]
See #214.
