### ISSUE TITLE
NonReentrant and AndThen

### ISSUE THREAD

**Issue by mdissel** [fluentscheduler/FluentScheduler#125]
When using this registry I expect that the next interval is not started when the last Job is finished.. but that is not the case..
```
public JobRegistry() {
	// Schedule multiple jobs to be run in a single schedule
	NonReentrantAsDefault();
	Schedule<Jobs1>().AndThen<Jobs2>().AndThen<Jobs3>().ToRunNow().AndEvery(2).Minutes();
}
```
or same result with
`Schedule<Jobs1>().NonReentrant().AndThen<Jobs2>().AndEvery(2).Minutes()`

**Comment by tallesl** [comment]
I'm sorry but I didn't quite understand what you meant. Did you expected the interval of 2 minutes to be made between the `AndThen` jobs?

There's no interval between the (child) jobs, the interval is between the schedule as a whole:


```cs
var registry = new Registry();

registry
    .Schedule(() => Write(1))   // writes "1"
    .AndThen(() => Write(2))    // writes "2"
    .AndThen(() => Write(3))    // writes "3"
    .AndThen(() => WriteLine()) // writes a new line
    .ToRunNow()
    .AndEvery(5).Seconds();

// after this line you get "123" (and a newline) in the console every 5 seconds
JobManager.Initialize(registry);
```

**Comment by tallesl** [comment]
I'm closing the issue, but feel free to ask anything further here.
