### ISSUE TITLE
Dependency Injection: GetJobInstance using lifetimescopes disposes registered components.

### ISSUE THREAD

**Issue by richardsorensson** [fluentscheduler/FluentScheduler#127]
I've noticed that when you start a new lifetime scope within getjobinstance<t>() the components being resolved for the job will be resolved before the job is being executed.

e.g.

public IJob GetJobInstance<T>() where T : IJob
{
    using (var scope = _scope.BeginLifetimeScope())
    {
        return scope.Resolve<T>();
    }
}

Once the job is resolved components might have been disposed as the lifetimescope is actually diposed and components registered along with it will also be disposed (probably those that implement idisposble or registered as instance per dependency).

Would be neat if there was a way to handle lifetimescope.

**Comment by tallesl** [comment]
I'm not familiar with lifetime scope (is this Autofac?) but if you need to dispose something after a job run I suggest looking into implementing IDisposable on the job. GetJobInstance duty is only to instantiate new jobs, it doesn't and shouldn't know when a job finished running.

(I'm not 100% sure if I understood your issue btw)

I'm closing the issue but feel free to comment it further on it.
