### ISSUE TITLE
MyJob Implementation With Dependency

### ISSUE THREAD

**Issue by nvsoares** [fluentscheduler/FluentScheduler#129]
Hi.
How to pass a dependency to the job builder?
See the Using it with ASP.NET section. 

```
    private readonly ILogger Logger;
    public SampleJob(ILogger myLogger)
    {
        this.Logger = myLogger;
        // Register this job with the hosting environment.
        // Allows for a more graceful stop of the job, in the case of IIS shutting down.
        HostingEnvironment.RegisterObject(this);
    }
```

When I do this the job does not run. If you remove the build dependency already runs.

**Comment by jplindgren** [comment]
I answer your problem at #126, let me know if it help you.

**Comment by tallesl** [comment]
I'll close this one and let the discussion happen on #126.
