### ISSUE TITLE
Clear jobs

### ISSUE THREAD

**Issue by JobaDiniz** [fluentscheduler/FluentScheduler#135]
How can I remove all jobs from JobManager?
Something like `JobManager.RemoveAll()`

**Comment by tallesl** [comment]
Right now you can't.

You are able to remove a single job if you gave it a name (`JobManager.RemoveJob()`) and you're also able to stop the all the jobs at once (`JobManager.Stop`).

That's useful, I'm flagging as `new feature`.

**Comment by tallesl** [comment]
Closed. Available on [5.3.0].

[5.3.0]: https://github.com/fluentscheduler/FluentScheduler/releases/tag/5.3.0
