### ISSUE TITLE
Concurrency Level

### ISSUE THREAD

**Issue by AlonAm** [fluentscheduler/FluentScheduler#136]
Is there a way to limit the number of concurrent jobs/threads?

**Comment by tallesl** [comment]
I'm afraid there isn't, you can only control reentrancy.

I don't think that this would be a good feature to be honest. We already have the complexity of a eventual job taking long than we expect and reentrancy, adding such limit to the mix would make very hard to understand what's going on (why the job started/not started).

**Comment by AlonAm** [comment]
Thanks a lot.
I've been using the library for a few months and it's working great.

See http://www.anystat.us
