### ISSUE TITLE
Problem With February Montly Schedule

### ISSUE THREAD

**Issue by netrevisanto** [fluentscheduler/FluentScheduler#138]
Hey Guys, thanks for the beautiful work with this lib. We are trying to set up a monthly scheduling task.
We are having an issue, with the On comand, when working with Monthly execution:

`var inicio = new DateTime(2017. 1,30);
JobManager.AddJob(acao, (s) => s.WithName(identificacao).ToRunOnceAt(inicio).AndEvery(intervalo).Months().On(inicio.Day).At(inicio.Hour, inicio.Minute));`

When the On() method is called, the date of nextExecution is March 2nd, and it should be in the very last day of next month, Feb 28th. 

I know if i can use the At() method in the Months() chain, we could have success, but the At method waits a MonthOnDayOfMonthUnit to do it, and we can see that only the On() method returns it.

Can you guys point me at right direction?

**Comment by tallesl** [comment]
Hi, sorry for the long delay.

It was a bug, I just fixed. I let you know here when it's published.

**Comment by tallesl** [comment]
Just published on [nuget.org](http://nuget.org), version 5.2.0.
