### ISSUE TITLE
Injection dependency in IJob

### ISSUE THREAD

**Issue by VenkateshSrini** [fluentscheduler/FluentScheduler#139]
Hi,
I would like to inject ILoggerFactory and database dependency to my Job. Please let me know how this needs to be done using ASP.NET core dependency injection

**Comment by tallesl** [comment]
Huh?

I don't quite got what you're saying, but you can either access a static/global dependency resolver from your job itself (after it's constructed by the library) or rely on a [job factory of you own](https://github.com/fluentscheduler/FluentScheduler#dependency-injection).

**Comment by VenkateshSrini** [comment]
@tallesl ,
Let me try to explain this with an example. We have two kinds of job
**on off jobs** These are jobs that will triggered when a threshold is reached and will process till the end condition is met. Say for example, if the database records exceeds 1000 records then the job will run every 5 minutes and process 500 records at a stretch, create a summary , the archives the record. Then once the threshold is 7000 the job stops.

**Periodic jobs** These jobs get triggered once and keeps running periodically and is stopped only in case of Maintainence. 
In either case we have a controller and we would like inject the job through IServiceCollection and receive the injected value in controller. Please let me know if this is possible
