### ISSUE TITLE
Installation error while adding into Xamarin Forms PCL

### ISSUE THREAD

**Issue by Anil86** [fluentscheduler/FluentScheduler#140]
#### Action:
Installed FluentScheduler in Xamarin Forms PCL having following profile:

![xamarin forms pcl profile](https://cloud.githubusercontent.com/assets/12828168/23591475/064df974-0217-11e7-87da-c71f3fa97669.PNG)

#### Expected behavior:
Package should install.

#### Actual behavior:
Package fails to install with following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'FluentScheduler 5.1.3'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0
```	

Which profile should I choose to make it compatible with Xamarin Forms PCL?

#### Configurations:

* FluentScheduler: 5.1.3
* Xamarin Forms: 2.3.3.193

**Comment by rubit0** [comment]
I think there is an issue with the nuget but if you build FluentScheduler locally the .dll will be accepted by the PCL.

**Comment by tallesl** [comment]
I never really used Xamarin, I can't help you (at least for now).
I added a "help wanted" label and a remark on README inviting others to help.

**Comment by johncharris** [comment]
To get this to build in for Xamarin you can download the source. Go in to the PortableLibary Settings and change the target to PCL. There are three places that `List.Foreach()` is used which isn't supported. That is pretty easy to fix those with regular `foreach` statements. Then you can build a PCL version of this.
