### ISSUE TITLE
Doesn't work in .net Core Web Api (v1.1.1)

### ISSUE THREAD

**Issue by EmmaHansson** [fluentscheduler/FluentScheduler#141]
It's pity, but I couldn't make this scheduler working.
```
 public void Start()
        {
            var registry = new Registry();
            JobManager.Initialize(registry);
            registry.Schedule<CrawlerJob>().ToRunNow().AndEvery(5).Seconds();
        }
```

and class job:

```
internal class CrawlerJob : IJob
    {
        private readonly ICrawl _crawl;

        public CrawlerJob(ICrawl crawl)
        {
            _crawl = crawl;
        }

        public void Execute()
        {
            var html = _crawl.RetrieveHtml();
        }
    }
```

In this case everything goes OK without exception. Only one trouble here is: Execute() method never fires.

Help needed.

**Comment by kdshinde** [comment]
I am too unable to get FluentScheduler but in .Net Framework 4.5.2 web api. I have used the ASP.Net example given in the documentation to schedule job in ASP.Net. Below is the code.

        [HttpPost]
        [Route("Schedule")]
        public IHttpActionResult ScheduleCall([FromBody] SchedulerModel schedulerModel)
        {
            var registry = new Registry();
            registry.Schedule<MyJob>().ToRunNow();
            JobManager.Initialize(registry);
            JobManager.StopAndBlock();
            return Json(new { success = true, message = "Scheduled!" });
        }

//Below is the job I want to schedule which for now is just writing text to a file
    public class SampleJob: IJob, IRegisteredObject
    {
        private readonly object _lock = new object();
        private bool _shuttingDown;

        public SampleJob()
        {
            HostingEnvironment.RegisterObject(this);
        }

        public void Execute()
        {
            lock (_lock)
            {
                if (_shuttingDown)
                    return;
              //Schedule writing to a text file
               WriteToFile();
            }
        }

        public void WriteToFile()
        {
            string text = "Random text";
            File.WriteAllText(@"C:\Users\Public\TestFolder\WriteText.txt", text);
        }

        public void Stop(bool immediate)
        {
            lock (_lock)
            {
                _shuttingDown = true;
            }            
            HostingEnvironment.UnregisterObject(this);
        }
    }

**Comment by tallesl** [comment]
Hi  @EmmaHansson,

Did you do what @xaclincoln suggested to you?

I'm closing this issue, but feel free to comment on it!

---

@kdshinde You should open an issue of your own.

Anyway, just after you initialized the job manager you are stopping it. That doesn't make much sense.

```cs
JobManager.Initialize(registry);
JobManager.StopAndBlock();
```
