### ISSUE TITLE
[Question] About NonReentrant mode

### ISSUE THREAD

**Issue by maratoss** [fluentscheduler/FluentScheduler#144]
#142 

Hi! Could you explain me?
If we have a NonReentrant job, does it means that the job must be run only once at the same time?
I created the test to demonstrate the trouble. Now it runs as minimum twice.

**Comment by tallesl** [comment]
You found a bug!

In your example:

```cs
schedule.NonReentrant().ToRunNow().AndEvery(1).Seconds()
```

`AndEvery` (child) is another schedule then `ToRunNow` (parent). For reentrancy matters, they should be considered the same schedule.

I just fixed it (dd84745), I'll soon release it in the next package version.

Thanks for reporting it!

**Comment by tallesl** [comment]
Just published on [nuget.org](http://nuget.org), version 5.2.0.
