### ISSUE TITLE
Version 5.1.4 doesn't support UAP/UWP any longer

### ISSUE THREAD

**Issue by HakanL** [fluentscheduler/FluentScheduler#145]
The latest version I can use is 5.0.0, the later versions give me this:

```
Restoring packages for C:\Projects\Other\IoStorm2\IoStorm\Service\project.json...
Package FluentScheduler 5.1.4 is not compatible with uap10.0 (UAP,Version=v10.0). Package FluentScheduler 5.1.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - netstandard1.5 (.NETStandard,Version=v1.5)
One or more packages are incompatible with UAP,Version=v10.0.
Package FluentScheduler 5.1.4 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm. Package FluentScheduler 5.1.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - netstandard1.5 (.NETStandard,Version=v1.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm).
Package FluentScheduler 5.1.4 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm-aot. Package FluentScheduler 5.1.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - netstandard1.5 (.NETStandard,Version=v1.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
Package FluentScheduler 5.1.4 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64. Package FluentScheduler 5.1.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - netstandard1.5 (.NETStandard,Version=v1.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64).
Package FluentScheduler 5.1.4 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64-aot. Package FluentScheduler 5.1.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - netstandard1.5 (.NETStandard,Version=v1.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
Package FluentScheduler 5.1.4 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86. Package FluentScheduler 5.1.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - netstandard1.5 (.NETStandard,Version=v1.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86).
Package FluentScheduler 5.1.4 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package FluentScheduler 5.1.4 supports:
  - net40 (.NETFramework,Version=v4.0)
  - netstandard1.5 (.NETStandard,Version=v1.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed. Rolling back package changes for 'Service'.
Time Elapsed: 00:00:01.8124030
========== Finished ==========
```

**Comment by tallesl** [comment]
I never really used UWP, I can't help you (at least for now).
I added a "help wanted" label and a remark on README inviting others to help.

**Comment by yanpaulo** [comment]
Hi, HakanL. Which version of Visual Studio are you using?
Have you tried to upgrade the UWP package in your Project? This may help.

**Comment by HakanL** [comment]
I'm on VS2017 and I've upgraded all packages, except FluentScheduler.

**Comment by yanpaulo** [comment]
Well that's sad News. Will test later.

**Comment by ipjohnson** [comment]
@HakanL the error is very non intuitive but I believe the error is because UWP 10 only supports upto .netstandard 1.4 as seen [here](https://github.com/dotnet/standard/blob/master/docs/versions.md) 

I did a quick test of grabbing the source and lowering the target version to 1.4 then ran the tests. Everything passed so there shouldn't be a downside to going down to 1.4 (maybe even 1.3)

**Comment by ipjohnson** [comment]
@tallesl I'd be interested in seeing FluentScheduler work on UWP. Would you accept a PR to retarget to a lower .netstandard? I don't believe there is anything dependent on 1.5 specifically.

**Comment by tallesl** [comment]
I'm OK in changing it to 1.4.

Since I'm not familiar with UWP, do you guys mind testing once again, this time the `.nupkg` package [here](https://github.com/fluentscheduler/FluentScheduler/releases/tag/untagged-f75b0a2a738fc3db9267)?

**Comment by ipjohnson** [comment]
@tallesl I was able to add the package to a UWP application, scheduled a job and it executed. From my perspective it looks good.

**Comment by HakanL** [comment]
I didn't have a chance to download the nupkg file above and test. But if it worked for @tallesl then I'm sure it will work for me too :)

**Comment by tallesl** [comment]
Published.

Thanks guys :+1:
