### ISSUE TITLE
Initialize with multiple Registry classes

### ISSUE THREAD

**Issue by mdissel** [fluentscheduler/FluentScheduler#146]
I want to dynamically load jobs from plugins. The preferred way is to use a Registry class, but currently the JobManager.Initialize method only accepts a single Registry class. Can this be changed to accepts params Registry[] / multiple registry classes?

**Comment by tallesl** [comment]
Looks like it's doable. I'll get back to you soon.

**Comment by tallesl** [comment]
It's done. I let you know here when it's published.

P.S.: I had to move `UseUtcTime` from `Registry` to `JobManager` (c6d50ae).

**Comment by mdissel** [comment]
Thanks!

**Comment by tallesl** [comment]
Just published on [nuget.org](http://nuget.org), version 5.2.0.
