### ISSUE TITLE
The job stop when application pool get recycled

### ISSUE THREAD

**Issue by xuqihe** [fluentscheduler/FluentScheduler#147]
`public class MyJob : IJob, IRegisteredObject`

Currently, the job stopped when the application pool get recycled. When i re-open the site, the job re-start running normally. How can i expect the job re-start even i don't re-visit the site after the application pool is recycled?

**Comment by mdissel** [comment]
Don't recycle the application pool ;) or find a way to automatically restart the website after a recycle

**Comment by tallesl** [comment]
Have you tried setting the [Idle Time-Out](https://technet.microsoft.com/library/cc771956.aspx) to zero?

![](http://i.imgur.com/50g6KAk.png)

**Comment by xuqihe** [comment]
Base the site on Azure and set always online.
