### ISSUE TITLE
How implement DI For Castle.Windsor

### ISSUE THREAD

**Issue by KANekT** [fluentscheduler/FluentScheduler#150]
How implement DI For Castle.Windsor

Any body have examples for use FluentScheduler with Castle.Windsor?

**Comment by tallesl** [comment]
There's an example of [Dependency Injection in the README](https://github.com/fluentscheduler/FluentScheduler#dependency-injection).

Even though the example doesn't particularly use Castle.Windsor, your `IJobFactory` implementation will end up being pretty similar.
