### ISSUE TITLE
IJob gets disposed, but constructor never called again

### ISSUE THREAD

**Issue by ronnyek** [fluentscheduler/FluentScheduler#151]
I've implemented DI container resolver and utilized with job manager as discussed in github documentation. Ultimately I want the job execute method to grab a new "scope" (undoubtedly not a responsibility of fluent scheduler). 

I noticed some instances of a instancePerLifetimeScope() weren't acting as I expected. I put logging into life cycle events for an IJob that implements IDisposable, and it hits constructor, execute, and dispose on completion of the first run. When it goes to fire off the next instance, it just calls execute (no attempt to hit the constructor again)

I guess my question is should the lifecycle of an IJob be that it gets created/disposed in each run?

**Comment by ronnyek** [comment]
I believe I jumped the gun a bit on this one... though I do think the scoping is a bit weird. I'll play with it a bit and see if I cant figure it out

**Comment by ronnyek** [comment]
Ok, so I experimented a bit more with this... all my services in this app are being activated as "InstancePerLifetimeScope". My job's constructor injects a Owned<JobService>. My job implements disposable.

In logging life-cycle events, I see this... 

[06:50:37 INF] Connecting...
[06:50:38 INF] Instantiating ProcessCRMJob
[06:50:38 INF] Executing ProcessCRMJob
[06:50:38 INF] Processing Daily CRM import...
[06:50:50 INF] Disposing ProccessCRMJob
...
[07:20:37 INF] Executing ProcessCRMJob
[07:21:05 INF] Disposing ProccessCRMJob

I see in code where the job disposal happens if IDisposable is implemented, and its pretty straightforward, but cant seem to get this to work properly. Owned<T> basically should setup its own subscope, but by the time I come around to executing job the second time, owned is disposed as if it is in-fact disposed, and likewise blows up.

**Comment by tallesl** [comment]
I'm not sure I quite get it...

Forgetting DI for a moment, are you saying that the library is reusing an instance of an `IJob` (instead of instantiating a brand new one)?

If so, can you post your job registry so I may try to reproduce it?
