### ISSUE TITLE
Consider Using NetStandard 1.3

### ISSUE THREAD

**Issue by johncharris** [fluentscheduler/FluentScheduler#152]
The project portable library is set to build with NetStandard 1.4. This prevents it from working on the current UWP apps. The library compiles for NetStandard 1.3, is there any reason not to use that?

**Comment by tallesl** [comment]
A few days ago I downgraded the requirement of 1.5 to 1.4 precisely due to folks complaining about UWP support (see #145).

Isn't this the same? Are you sure you can't make it work with 1.4?
