### ISSUE TITLE
More flexible job events

### ISSUE THREAD

**Issue by Zero3** [fluentscheduler/FluentScheduler#154]
Use case: I have a number of background jobs, including one that runs every couple of minutes. I also have a `JobStart` event handler that logs job starts to my log file. I would like to be able to skip logging for the job that runs every couple of minutes to avoid spamming my log files.

Possible solutions:

1) Add more information to the `JobStartInfo` class sent to `JobStart` event handlers to support the use case.

2) Job groups with the possibility of attaching different event handlers to different groups (https://github.com/fluentscheduler/FluentScheduler/issues/122).

3) Non-static `JobManager` (https://github.com/fluentscheduler/FluentScheduler/issues/148)

**Comment by tallesl** [comment]
It's not ideal, but you can workaround it by assigning a name when scheduling your job and then read that name on `JobStartInfo`.

> Job groups with the possibility of attaching different event handlers to different groups

Hey, have you been using my laptop?

Just kidding. I have precisely that (and the non-staticness) in an yet to finish implementation of the new library design (mentioned on #148). It currently lives only on my machine.
I'm unable to give the proper attention to it these days, but I'll probably get things rolling on next month.

I'm closing the issue but feel free to comment it further.
