### ISSUE TITLE
Using FS in NetStandard lib and referencing it in net4xx results in FileLoadException

### ISSUE THREAD

**Issue by marcwittke** [fluentscheduler/FluentScheduler#159]
See repro: https://github.com/marcwittke/FluentSchedulerLoaderExRepro

The ```NetStandardLib``` targets net standard 1.4, the ```WebApplication8``` targets .net462. 
Line 31 in ```Startup.cs``` simulates the container initialization in my real application. 
```
var types = typeof(MyRegistry).Assembly.GetExportedTypes();
```

But even this basic line throws:
![unbenannt](https://user-images.githubusercontent.com/4075651/27546290-c64d3542-5a68-11e7-9cce-a88219f7819b.PNG)

First check: assembly is present in the output folder
![unbenannt](https://user-images.githubusercontent.com/4075651/27546372-fadb2648-5a68-11e7-944b-d45d6e446aa2.PNG)

**Comment by tallesl** [comment]
I couldn't open your project, tried in both VS 2013 and 2015. Inspecting the .csproj, I find it a rather clearer XML than usual. Is that VS 2017?

**Comment by marcwittke** [comment]
Yes, this was done wih VS2017. However, I think it's a general issue when referencing ```netstandard``` in a ```netfx``` library that is referenced by a full blown ```netfx``` startup project. The same issue occured later with another lib, too.

I worked around this issue by moving the code from the lib to the startup project, so it isn't blocking me right now, but the architecture clearlyness suffers a little bit.

**Comment by nrjohnstone** [comment]
I've bumped into this as well just in the last few weeks, I've added another repo here .. https://github.com/nrjohnstone/fluentScheduler-netcore-issue 

I'll pick this up and look into it if you want @tallesl as it will be a blocker for some of the things I'm working on at the moment

**Comment by nrjohnstone** [comment]
Looking into this at first glance I think I see the problem, there are two solutions, one built with a portable library targeting netstandard 1.4 and one targeting full frameworks. This means indeed the two binaries will not have the same manifest at all.

I'm going to submit a PR that goes down to a single net standard project which targets both 4.0 and netstandard 1.4 and this is the correct way to multitarget for packages as the binaries will end up with the same manifest

**Comment by nrjohnstone** [comment]
@tallesl  - I've got it fixed in this branch here,

https://github.com/nrjohnstone/FluentScheduler/tree/feature/multitarget-fix

however I want to know if the TestApplication is worth fixing as currently it references a few packages that I cannot find on nuget at all eg FolderCleaner, Fresh and L ?

**Comment by nrjohnstone** [comment]
@tallesl are you ever going to look at this?

**Comment by tallesl** [comment]
There are issues on using the current version of the library with .NET Core (#118, #159, #208).

I think those came from the current support being a portable library thingy, made prior to core 2.0, and poorly tested by me (sorry).

I'm relunctant on making changes on the current version that lives on master, however the current library redesign (#214) is been done entirely in .NET Core.

I kindly ask you folks to wait for the redesign to be done.

**Comment by nrjohnstone** [comment]
Since the .NET Core version is a complete rewrite, and this is a change to
a version currently used in MANY production environments, I would suggest
you are wrong in ignoring this fix as you cannot expect everyone to just
upgrade to the .NET Core version especially when you have made it
completely backwards incompatible.

Please reconsider at least adding this PR that fixes the multitargetting
for the current main version for those people who want to slowly migrate
some of their applications to NET Core without having to re-write all of
their scheduling code as well. There have been A LOT of bug fixes to the
current stable release and moving to new code base in NET Core is that last
thing many people will want to be considering at this moment (or whenever
the NET Core version is released).
