### ISSUE TITLE
Dependency Injection in an IJob

### ISSUE THREAD

**Issue by cswolfe** [fluentscheduler/FluentScheduler#160]
I understand this issue was covered previously, but I have not found a solid answer. Essentially my problem is that I have holidays in a database and if the day the job runs is a holiday, I want it to not run. Since I am using the repository model, which required dependency injection, I require dependency injection within the Job implementation in order to achieve this goal. Is there any way to achieve dependency injection for a job? If this can be done with a JobFactory, please provide a better implementation than the StructureMap example.

**Comment by tallesl** [comment]
> I require dependency injection within the Job implementation in order to achieve this goal

No, you don't.
Just check if it's a god damn holiday and don't schedule the job, or, if done inside the job, just return early.

Dependency injection is supposed to empower you, and look at you, not being able to do something as simple as checking if it's a holiday. C'mon folks, take your heads out of the sand, not every if/else scenario must be fulfilled by a custom type magically injected in another class.

Sorry for the rant, but it's flabbergasting how often DI frameworks hurts software by adding an incredibly amount of complexity and you guys just passively accepts it.

**Comment by CooperWolfe** [comment]
I was able to solve my problem using dependency injection which was necessary to get the holidays that users create from a database. This may include holidays that are not official or even made up. You did not understand my use case nor trust my word on my issue. Please make an effort to keep the github community supportive, understanding, and positive as is the goal not only of GitHub, but open source as a whole. I am saddened to see this kind of attitude in a public coding community. I will be reporting this instance and I hope there are no hard feelings.

**Comment by pkmccaffrey** [comment]
@CooperWolfe - I too am using EF with the repository pattern, and I needed to inject my "services" (repositories) into my jobs.  Implementing IJobFactory and setting it on the JobManager seems to be working properly.  Just make sure your jobs are registered with your DI container with a proper "lifetime" so that the disposal of your EF contexts (and any other disposable objects) is handled correctly.

**Comment by CooperWolfe** [comment]
Just to help the community, to achieve dependency injection, I made the JobManager.Initialize method static and then injected what I needed by hand at the end of the Startup.ConfigureServices method:
`
  services.AddScoped<IJob, ProgressJob>();
  services.AddSingleton<SchedulerRegistry, SchedulerRegistry>();
  JobManager.Initialize(services.BuildServiceProvider().GetService<SchedulerRegistry>());
`

**Comment by CooperWolfe** [comment]
Thank you @pkmccaffrey

**Comment by tallesl** [comment]
> Please make an effort to keep the github community supportive, understanding, and positive as is the goal not only of GitHub, but open source as a whole.

Quit playing the victim.

Before mindlessly stating things as such, I suggest you to read some the other issues around here.
You'll not only find folks helping it each other but also a conversation or two on thinking critically about dependency injection that could teach you a lot.

>I will be reporting this instance

You're reporting what? To whom? What's that even mean? 
Jesus...
