### ISSUE TITLE
Problem with Concurrent jobs

### ISSUE THREAD

**Issue by vilix13** [fluentscheduler/FluentScheduler#161]
```
class testJob : IJob
        {
            public void Execute()
            {
                MessageBox.Show("hello!");
            }
        }
```
NonReentrant work only with call like this:
```
JobManager.AddJob<testJob>(s => s.NonReentrant().ToRunNow().AndEvery(1).Seconds());
```
But I want also using "run and forget"  with NonReentrant like:
```
            JobManager.AddJob<testJob>(s => s.NonReentrant().ToRunNow());
            JobManager.AddJob<testJob>(s => s.NonReentrant().ToRunNow());
            JobManager.AddJob<testJob>(s => s.NonReentrant().ToRunNow());
```
But 3 jobs runs concurrently. Can I do this with FluentScheduler?

**Comment by tallesl** [comment]
That doesn't work because the library see is it as 3 separate schedules. The (non) reentrancy is per schedule, not per job.

But you can set one job to fire right after another within the same schedule with `AndThen`.
