### ISSUE TITLE
Duplicate schedule start after a certain unknown time 

### ISSUE THREAD

**Issue by ashishbhagasra** [fluentscheduler/FluentScheduler#162]
Hi,

I am trying to create schedules dynamically using fluent scheduler.
There is a schedule A running at specific interval and looks for schedule entries in the database and schedules them. I am using fluent scheduler with dot net core console application.
After a certain period of time, the scheduler starts executing duplicate schedules at the same time. In database, I am unique entries for each schedule. More than 1 schedule can have same execute datetime as well.

`
using FluentScheduler;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Globalization;

namespace MyScheduler
{
    public class Program
    {
       
        public static IEnumerable<DbSchedule> schedules = new List<DbSchedule>();

        public static void Main(string[] args)
        {
            JobManager.UseUtcTime();  
            var registry = new Registry();
			
            registry.NonReentrantAsDefault();

            JobManager.Initialize(registry);

            Action fetchJobSchedules = new Action(() =>
            {
                schedules = FetchSchedulesFromDb(); // Fetch schedule list from Database
                CreateSchedules();
            });
            JobManager.AddJob(fetchJobSchedules,
                              (s) => s.WithName("A")
                              .ToRunEvery(30).Seconds());

            Console.ReadLine();
        }
		
        private static void LogScheduleEventDate(int id, string type)
        {
			// Log to Database	using db context
            Dbcontext.LogScheduleEventDate(id, type, DateTime.Now);
        }

        private static void InsertJob(int id)
        {
            LogScheduleEventDate(id, "Start");
            Console.Write("Job Started! " + id);
           
                // Fire and forget
                Task.Run(() =>  DoSomeScheduledJobById(id)); // When duplicate schedules run more than once, this is executed more than once too.
           
            LogScheduleEventDate(id, "End");
        }

        private static void CreateSchedules()
        {
            foreach (var item in schedules)
            {
               if(ScheduleIsNotScheduledByFluentYet)
               {
                 // Schedule job using fluent scheduler
                Action InitializeSchedule = new Action(() => InsertJob(item.Id));
				JobManager.AddJob(InitializeSchedule,
						   (s) => s.WithName(item.Id.ToString())
						   .NonReentrant()
						   .ToRunOnceAt(item.date.AddMinutes(-1).ToUniversalTime())
						   );
		  }
            }
        }

    }
}

`
Below are the duplicate entries in database:
![duplicateentries](https://user-images.githubusercontent.com/13831357/27909261-7e98c542-626d-11e7-881d-daf02e5f5de2.PNG)

**Comment by tallesl** [comment]
The `CreateSchedules` *seems* to be fine, but I'm not quite sure.
I guess the problem is on `Main`.

You are creating a registry:

```cs
var registry = new Registry();
		
registry.NonReentrantAsDefault();
```

Then you create a job with `AddJob`, ignoring the registry you just created:

```cs
JobManager.AddJob(fetchJobSchedules,
                  (s) => s.WithName("A")
                  .ToRunEvery(30).Seconds());
```

This job is reentrant, I believe this is the source of your error.
If you provide a reproducible console application I may further help you.
