### ISSUE TITLE
Signed DLL, please

### ISSUE THREAD

**Issue by LRomano72** [fluentscheduler/FluentScheduler#164]
Hi, just wondering if you are able to create an "signed dll" package as we require it for a security project and we don't want to create our own from your source code as it would create maintenance and upgrade issues.
You can tell your package is popular when you get this type of request. :-)

Thanks for your time on this!

**Comment by tallesl** [comment]
I'm sorry but you'll have to do it on your end.

The library had such support before (#13) but the reality is that (almost) nobody really cares for it.  At some point such support simply went away (was probably me).

Also, having the private key public, which was the solution, doesn't feel right.

**Comment by MattacksWTW** [comment]
@tallesl  If you want your library to be 'proper' and to have a wide usage professionally it will have to be signed.
Not being signed is probably a blocker on us
