### ISSUE TITLE
Scheduler doesn't work 

### ISSUE THREAD

**Issue by ElanCao** [fluentscheduler/FluentScheduler#170]
I tested for many times in my asp.net project. but it's strange.

`Schedule<EmailJob>().ToRunEvery(1).Days().At(0, 0);    //doesn't work`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(00, 00);    //doesn't work`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(00, 05);    //doesn't work`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(01, 00);    //doesn't work`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(1, 0);    //doesn't work`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(1, 00);    //doesn't work`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(1, 05);    //doesn't work`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(01, 05);    //works well`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(1, 1);    //doesn't work`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(1, 2);    //doesn't work`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(1, 4);    //doesn't work`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(1, 5);    //works well`
`Schedule<EmailJob>().ToRunEvery(1).Days().At(1, 6);    //works well`

Anyone else has the same issue?

**Comment by usmankaiiz** [comment]
I am having issues with scheduler too

this.Schedule(someMethod).ToRunNow(); // this works
this.Schedule(someMethod).ToRunEvery(10).Seconds(); // doesn't work

**Comment by marktrue** [comment]
i guess u should check the settings of IIS

"Application pool"  -> "advanced settings" of your application -> "idle time-out"  and "recycling interval"(someting like that, i guesss. i dont use English GUI)  Should Be ZERO

cause IIS will stop worker process when there is no http request and restart process every XX minutes
in this case your schedule may not work

**Comment by tallesl** [comment]
Check [#147](https://github.com/fluentscheduler/FluentScheduler/issues/147#issuecomment-295551023)
