### ISSUE TITLE
Can we use this library for Windows Service applications?

### ISSUE THREAD

**Issue by mdawood1991** [fluentscheduler/FluentScheduler#171]
I was just wondering has anyone tested this library for windows services?

**Comment by Xanneth** [comment]
@mdawood1991 That's exactly what I'm using it for!

**Comment by mdawood1991** [comment]
@Xanneth  in the OnStart method you would be registering the jobs to the Job Manager

like this:

        public static void Start(string[] args)
        {
            // onstart code here
            JobManager.Initialize(new MyRegistry());
        }


but do we have to unregister/stop the jobs in the OnStop?

**Comment by Xanneth** [comment]
@mdawood1991 As a disclaimer, I just want to say I'm not sure what "best practice" is here... I can only tell you what I'm doing and what works.  The following pattern is working on a very large application.

I stop all jobs in: OnStop, OnShutdown, OnPause, and OnContinue.  I simply call to RemoveAllJobs to clean it all up.

Then, during OnStart I relaunch all the jobs.  I do this by calling a method that uses Assembly.GetTypes() to find all registries throughout my entire application (they're all in one namespace but I wanted to catch any regardless of where they are) and then use Activator.CreateInstance() to initialize them all into an array of instances.  Then I pass that array into JobManager.Initialize() during OnStart.

**Comment by mdawood1991** [comment]
@Xanneth ok thanks -

**Comment by Xanneth** [comment]
It's worth pointing out that I'm pretty certain you don't actually need to clean up resources between OnPause and OnContinue.  I'm pretty certain your AppDomain doesn't get unloaded; however, I wasn't certain of the specifics and I also wasn't concerned about performance penalties during service start up.  I chose to just nuke it all then try to figure it out.  :/

**Comment by tallesl** [comment]
@Xanneth
Thanks for the support 👍
