### ISSUE TITLE
Cannot access a disposed object exception when method invoked by fluent scheduler job

### ISSUE THREAD

**Issue by moraleslos** [fluentscheduler/FluentScheduler#173]
I'm getting the "Cannot access a disposed object" exception during a call to a method that uses a DI-injected dbcontext (Transient-scoped)-- most likely the dbcontext was already disposed when being invoked. The method is being invoked as a job by fluent scheduler:

```
JobManager.AddJob(
   () => ExecuteUpdateDbContext(),
   (s) => s.ToRunNow().AndEvery(60).Minutes()
);
```

Also tried async version to no success:
```
JobManager.AddJob(
   async () => await Task.Run(() => ExecuteUpdateDbContext()),
   (s) => s.ToRunNow().AndEvery(60).Minutes()
);
```

The ExecuteUpdateDbContext method works in any under circumstance except when used by fluent scheduler. Do I need to do something special with my ExecuteUpdateDbContext method to make it work with fluent scheduler?

ASP.NET Core 2.0, EF Core 2.0, FluentScheduler 5.3.0

**Comment by pkmccaffrey** [comment]
Where are you resolving your context?  How/when are you disposing it?

I'm injecting my context into jobs with Unity, but am using a Hierarchical lifetime instead of Transient.  This shouldn't cause any problems though -- just a different approach at lifetime management.

**Comment by moraleslos** [comment]
@pkmccaffrey Thanks for the response.  It's all resolved in startup:

```
public void ConfigureServices(IServiceCollection services)
{
services.AddDbContext<MyDbContext>(options => options.UseSqlServer(Configuration["Data:DbConnectionString"]));

services.AddMvc();
services.AddTransient<IUpdateAccountService, UpdateAccountService>();
}
```

And in my UpdateAccountService class:

```
public class UpdateAccountService: IUpdateAccountService
    {
        private readonly MyDbContext dbContext;

        public UpdateAccountService(MyDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

       public void ExecuteUpdateDbContext(Account account)
       {
         dbContext.Add(account);  // fails here
       }
}
```

**Comment by pkmccaffrey** [comment]
@moraleslos - I'm not familiar with whatever DI container you are using, but if I'm reading that code correctly, you've registered `IUpdateAccountService` as a transient instance of `UpdateAccountService`.  This service takes an instance of your context as an injected constructor parameter.  However, I don't see the context itself registered as being "transient."  My guess is the app is creating one instance of `MyDbContext` and trying to share it, but this doesn't work because it gets disposed at some point.

Anyway, my guess is there's a way to register your context as transient.

**Comment by tallesl** [comment]
I'm closing the issue but feel free to keep the conversation going.
Thanks for the help @pkmccaffrey.

**Comment by laccf** [comment]
How the problem was solved?

**Comment by martinussuherman** [comment]
I solve the dbcontext problem (I use pooled dbcontext fyi) using idea from: https://github.com/mjrousos/MultiThreadedEFCoreSample using fix 2: Create DbContexts, as needed, from DI-delivered DbContextOptions

Here's the link to my repo with the solution: https://github.com/martinussuherman/PsefApiOData/tree/dev-fluent-scheduler
Hope this helps anyone that might still have trouble with this.

Regards,

Martinus
