### ISSUE TITLE
Registry : public Schedule Schedule(Action job)

### ISSUE THREAD

**Issue by stephdep** [fluentscheduler/FluentScheduler#174]
Hi,
Great Library.

Using the meantioned method, how to get the name of the Schedule set ?
There exist a method Schedule Schedule(Action action, string name), however this one is private.

Why not make the private one public, it seems the public one just calls the private one, passing null for the  name  argument

Steph

**Comment by tallesl** [comment]
I don't quite get what you're saying. The private method you mentioned is [this one](https://github.com/fluentscheduler/FluentScheduler/blob/de0116c/Library/Registry.cs#L86-L101), right?

The private method that we're talking about here is just *setting* the name of the schedule. To set the name of a schedule yourself, you can call the publicly available `WithName` method when fluently setting up your schedule.

As for *getting* the name of the schedule, there's a public `Name` property on the `Schedule` class.
You may find the desired instance by calling `GetSchedule`, `RunningSchedules` or `AllSchedules` of `JobManager`.

You can also get the name of the schedule on `JobStart`, `JobEnd` and `JobException` events (also on `JobManager`). This is probably the best option.
