### ISSUE TITLE
API Extension: StopAndKill

### ISSUE THREAD

**Issue by domdeger** [fluentscheduler/FluentScheduler#179]
Hello, i'd like to propose a API Extension that allows us to Stop a schedule and kill running tasks.
As far as i understand this library there is no possibility to achieve this currently.

Regards,
domdeger

**Comment by tallesl** [comment]
FluentScheduler uses tasks (and not threads) internally, and you can't kill one of those. Even if you could, I don't like the idea of killing some task leaving things unfinished.
