### ISSUE TITLE
HowTo: Some usage questions of recurring events

### ISSUE THREAD

**Issue by delfuria** [fluentscheduler/FluentScheduler#18]
Hi,
i don't know if this is the right place for my question because i haven't find anything on the web about recurring task:
I need to run my task with this conditions:
1) run a task every day from 1/6/2013 until 15/7/2013
2) run a task every Monday, Friday and Sunday of every week,
3) run a task every 2, 5 and 10 of June every year
4) run a task every 2nd and 4th friday of every month

Thanks in advance
Stefano

**Comment by mshami85** [comment]
Hi

> run a task every Monday, Friday and Sunday of every week

Can i name them all as one name ?? i.e

```
Schedule<MyTask>().WithName("Job1").ToRunEvery(1).Weeks().On(DayOfWeek.Monday).At(8, 30); // Note: the .At(8, 30) portion is optional - if omitted, the task will run at 12am.
Schedule<MyTask>().WithName("Job1").ToRunEvery(1).Weeks().On(DayOfWeek.Friday).At(8, 30);
Schedule<MyTask>().WithName("Job1").ToRunEvery(1).Weeks().On(DayOfWeek.Sunday).At(8, 30);
```

So i can remove them all by using 
`JobManager.Remove("Job1");`

and keep other jobs working
