### ISSUE TITLE
Inconsistency with how ToRunEvery(n) is handled on weeks.

### ISSUE THREAD

**Issue by thulani-chivandikwa** [fluentscheduler/FluentScheduler#181]
On weeks doing ToRunEvery(1).Weeks() would mean the current week is skipped and this can be avoided ToRunEvery(0).Weeks(). While this is a great feature it is not consistent with how Days for instance works and is not obvious - I do acknowledge though that the documentation covers this. Something like ToRunEvery().WeeksExclusive() or simillar sounds like a more intuitive way to expose this feature?

**Comment by tallesl** [comment]
I completely agree. The documentation helps, but the behavior isn't obvious even after you just read it. I once had to explain to a coworker a couple of times why that is the case.


In one hand this doesn't feel like a major change, just a little extra method. In the other hand it does, it may (silent) break for folks relying on the old way.

Here's what I'm gonna do: right now I'm dedicating most of my efforts on the library [redesign](https://github.com/fluentscheduler/redesign). I'll make sure I fix this there and, for now, I'll leave this issue open as "new feature".

**Comment by VitorCioletti** [comment]
Fixed in the newest version. See #214 for release info.
