### ISSUE TITLE
.net core example

### ISSUE THREAD

**Issue by apis3445** [fluentscheduler/FluentScheduler#182]
Hi! I try to include the example in the readme, but this method is not exist in structure map, how I can replace this method with other?
ObjectFactory.Container.GetInstance<T>()

**Comment by tallesl** [comment]
As discussed in other issues, I plan to ditch the dependency injection support of the library in the future. I just replaced the example on README with a note about it.

As for your question, just replace `ObjectFactory.Container` [in the example](https://github.com/fluentscheduler/FluentScheduler/tree/de0116c#dependency-injection) with your container instance (as seen [here](http://structuremap.github.io/quickstart/)).
