### ISSUE TITLE
fluent scheduler call controller action

### ISSUE THREAD

**Issue by ruurdeijzinga** [fluentscheduler/FluentScheduler#184]
How do I call a controller action in fluent scheduler ? I tried this but that does not work.
I would like to run /Welcome/index
Schedule(() => TestCronJob.Controllers.WelcomeController.ToRunEvery((1)).Hours().At(30);

**Comment by tallesl** [comment]
Are you talking about a ASP.NET controller?

AFAIK, it doesn't make sense to call a controller action directly from code (unless, maybe, when unit testing).
Your code is probably not even compiling (unless `WelcomeController` is a `IJob`).

What exactly are you trying to achieve? I'm closing the issue but feel free to comment it further.
