### ISSUE TITLE
How to get Next Run time In Job

### ISSUE THREAD

**Issue by Usman235** [fluentscheduler/FluentScheduler#186]
How to get next run time in a job  method `Execute`

```
public class ScheduleJob : IJob
    {

 public async void Execute()
        {
//here i need next run time.
       }
 }
```

I have search but didn't find any thing . Do someone have done this before ?

**Comment by tallesl** [comment]
You can't get the next run inside `Execute`, but you can get it on `JobEnd` event:

```cs
using FluentScheduler;
using System;
using System.Threading;

public class Program
{
    static void Main(string[] args)
    {
        var registry = new Registry();
        registry.Schedule(() => Console.WriteLine($"Job called ({DateTime.Now}.")).ToRunNow().AndEvery(10).Seconds();

        JobManager.JobEnd += info => Console.WriteLine($"Job just ended. Next run {info.NextRun}.");
        JobManager.Initialize(registry);

        Thread.Sleep(Timeout.Infinite);
    }
}
```

Does that work out for you?

**Comment by Usman235** [comment]
@tallesl thanks for your response.

Actually i need  `NextRun` in `Execute` method for some calculation. 

Solution which you suggested is not a workaround for my situation.

**Comment by tallesl** [comment]
Unfortunately that's not possible at the moment.
If you don't mind me asking, why do you need this?

**Comment by Usman235** [comment]
i'm trying to calculate the time difference like.

`var timeDiff=nextRun-currentTime ;`

then 

```
var reportStartTime=//then will calculate report start time according to `timeDifference`.
var reportEndTime=currentTime.

```
In this way i'm trying to get the data from server between `reportStartTime` and `reportEndTime`.
