### ISSUE TITLE
User Based Jobs

### ISSUE THREAD

**Issue by cnikolov** [fluentscheduler/FluentScheduler#187]
Hi 

Happy Christmas

Hope you can help.

I would like to add/remove new jobs when needed using the userId.

So i can do something like.
long userid = 1234;
registry.userid = userid;

registry.Schedule(() => GetNewOrders().Wait())
                    .ToRunNow()
                    .AndEvery(1)
                    .Hours();

JobManager.JobManager.StopAndBlock(registry.userid);

**Comment by VitorCioletti** [comment]
This is not possible in the current version of the library. We are redesigning it and this feature will be soon added in the new version. sry 

Happy Christmas :)

**Comment by tallesl** [comment]
(an incredibly late) Happy Christmas!

With the `JobManager` already initialized, you can do:

```cs
// adding
JobManager.AddJob(
    () => Console.WriteLine("Peekaboo!"),
    schedule => schedule.WithName("MySillyJob").ToRunEvery(1).Seconds()
);

// removing
JobManager.Remove("MySillyJob");
```
(@VitorCioletti probably didn't know/forgot about that part of the library, not his fault though, I forgot  about `Remove` myself for a second before writing this)

You cited `StopAndBlock`, but note that `JobManager.Remove` works more like `Stop` (it doesn't block).

We have an [ongoing redesign of the library](https://github.com/fluentscheduler/redesign/issues/3), which one of the aims is to provide a flexible job management (right now I have a non-static job manager plus some sort of job tagging in mind). If that sparks your interest, stay tuned there!
