### ISSUE TITLE
Job run twice at the same time

### ISSUE THREAD

**Issue by Magee-Yang** [fluentscheduler/FluentScheduler#188]
Job run twice when I use the following code:

JobManager.AddJob(job, njb => njb.WithName(jobName).ToRunOnceAt(nextTriggerTime).AndEvery(interval).Days().At(nextTriggerTime.Hour, nextTriggerTime.Minute));

Please check whether it is a bug, thanks!

**Comment by tallesl** [comment]
I couldn't reproduce...

Do you have an exact use case that I can take a look at?

**Comment by Magee-Yang** [comment]
Sorry, now I also cannot reproduce, this week it works very well on my computer.
Strangely, my colleague did not encounter this problem for the same code.
If encounter next time, I will provide the detailed code for your check. Thanks!

**Comment by tallesl** [comment]
No problemo. Thanks for reporting anyway. 😄

**Comment by ArtemAvramenko** [comment]
After three years of using FluentScheduler, I have faced the same problem. Server was in uptime two last weeks without any changes, but the problem appeared yesterday. Now I need to restart production server.

The problem is very hard to reproduce, so please take a look to scheduler logic, maybe you find the cause.

**Comment by tallesl** [comment]
If such problem does exist, it's a nasty one.

I know it's hard to give an exact reproducible use case, but do you have further information on it?

Does it happened more than once? What's your schedule? Does your job perform some long running operation?

**Comment by nunezmarco** [comment]
This happens to me from time to time on weekly jobs

  Action someMethod = new Action(() =>
            {
                _fluentSchedulerService.SaveWeeklyReports();
            });

            DayOfWeek Sunday = DayOfWeek.Sunday;
            this.Schedule(someMethod).NonReentrant().ToRunEvery(0).Weeks().On(Sunday).At(23, 50);
