### ISSUE TITLE
how to get httpcontext in exception

### ISSUE THREAD

**Issue by mwinner313** [fluentscheduler/FluentScheduler#189]
i'm using elmah to log my errors ,and i need a way to catch httpcontext like this 
```
 JobManager.JobException += info =>
            {

                try
                {
                    ErrorSignal.FromContext(info.Exception.HttpContext).Raise(info.Exception);

                }
                catch (Exception e)
                {

                }
            };
```

**Comment by mdissel** [comment]
There's no httpcontext inside a background job. The job is running on a different thread.

**Comment by tallesl** [comment]
Yup. `HttpContext.Current` is tied to the request thread, a different thread than the one that FluentScheduler will spawn to run its job.

[This SO answer explains it in detail](https://stackoverflow.com/a/24759917).
