### ISSUE TITLE
Complex Schedule - Prevent Overlapping?

### ISSUE THREAD

**Issue by ajhalls** [fluentscheduler/FluentScheduler#191]
I have this set of schedules I am trying to kick off

```
var registry = new Registry();
registry.NonReentrantAsDefault();
registry.Schedule<DefinitionSync>().ToRunNow().AndEvery(1).Days();
if (Settings.Default.LastFullUpdate == "0")
{
	registry.Schedule<InitialSync>().ToRunNow();
}
else
{
	registry.Schedule<UpdatesForServer>().AndThen<UpdatesFromServer>().ToRunNow().AndEvery(2).Minutes();
}
JobManager.Initialize(registry);
```
The issue I am having is that within the InitialSync I get the customer lists and appointments, these things have to be processed in sequence since you can't have appointments in the DB that don't connect with a customerID.

I only want it to run once per installation, but then after that runs I need to run `UpdatesForServer` and `UpdatesFromServer` every couple minutes, but they can't be run before the `InitialSync` is done, which could take anywhere from 5 minutes to 15.

Is there any way to do something like **.WaitForJob(InitialSync)**:
 ```
if (Settings.Default.LastFullUpdate == "0")
{
	registry.Schedule<InitialSync>().ToRunNow();
	registry.Schedule<UpdatesForServer>().AndThen<UpdatesFromServer>().ToRunNow().AndEvery(2).Minutes().WaitForJob(InitialSync);
}
else
{
	registry.Schedule<UpdatesForServer>().AndThen<UpdatesFromServer>().ToRunNow().AndEvery(2).Minutes();
}
```

**Comment by tallesl** [comment]
No, there's nothing like "WaitForJob".

You can check some external state (a flag somewhere like a database or a file) on UpdateFromServer, doing or not doing the intended work based on such state.

Another option is schedulling the UpdateFromServer job at the end of InitialSync (using JobManager.AddJob).
