### ISSUE TITLE
Add optional timeout to JobManager.StopAndBlock()

### ISSUE THREAD

**Issue by bitchkat** [fluentscheduler/FluentScheduler#192]
It would be nice to have an alternate form of JobManager.StopAndBlock() that takes a timeout parameter.  This allows giving jobs currently running a chance to finish without the potential of them hanging forever,

**Comment by bitchkat** [comment]
For now, I am working around this by doing
`Task.Run(() => JobManager.StopAndBlock()).Wait(10000);`

**Comment by tallesl** [comment]
Coming on #214 .
