### ISSUE TITLE
UnitOfWork Dependency Injection not working with FluentScheduler in Asp.Net Core 

### ISSUE THREAD

**Issue by umar-ulabs** [fluentscheduler/FluentScheduler#195]
I have the following classes 
    public class Communicator : IJob
    {

        private readonly IUnitOfWork _unitOfWork;
        public Communicator(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }
       
        public void Execute()
        {           
            var customers = _unitOfWork.Customers.GetAll();        
            using (var client = new HttpClient())
            {               
                var response = client.PostAsync("URL",
                    new StringContent(JsonConvert.SerializeObject(customers),
                        Encoding.UTF8, "application/json"));
                
            }
        }
    }
    public class ScheduledJobRegistry : Registry
    {
        public ScheduledJobRegistry()
        {
            Schedule<Communicator>()
                .NonReentrant() // Only one instance of the job can run at a time
                .ToRunOnceAt(DateTime.Now.AddSeconds(3))    // Delay startup for a while
                .AndEvery(2).Seconds();     // Interval

            // TODO... Add more schedules here
        }
    }
// In Startup.cs 
I have services.AddScoped<IUnitOfWork, UnitOfWork>();
and In Configure method I added 
 JobManager.Initialize(new ScheduledJobRegistry());

the IUnitOfWork is always null in Communicator class. Can Anybody help?

**Comment by tallesl** [comment]
[Sorry, but dependency injection it's on its way to be deprecated](https://github.com/fluentscheduler/FluentScheduler#dependency-injection).
You can find some better ways to get around it on #148.
