### ISSUE TITLE
NextRun before the schedule runs

### ISSUE THREAD

**Issue by Pentico** [fluentscheduler/FluentScheduler#196]
Hi

I noted NextRun is only calculated after the first time the schedule is run,

Would it be possible to populate this value before executing the first schedule?

**Comment by tallesl** [comment]
Hey,

If I'm not mistaken, `NextRun` is calculated when the job manager is initialized (and not after its first run), which seems reasonable.

Can you be more specific on your use case?

I'm closing the issue but please comment it further.
