### ISSUE TITLE
Days unit difference between today or tomorrow

### ISSUE THREAD

**Issue by mdissel** [fluentscheduler/FluentScheduler#198]
When you specify RunEvery(1).Days() or RunEvery(0).Days() the result is the same, the schedule is run tomorrow. Shouldn't this be the same logic as with weeks?

https://github.com/fluentscheduler/FluentScheduler/blob/2404cf03713d10a6f82030ff533eba750bb7bc29/Library/Unit/DayUnit.cs#L14

https://github.com/fluentscheduler/FluentScheduler/blob/2404cf03713d10a6f82030ff533eba750bb7bc29/Library/Unit/WeekUnit.cs#L14

I want to schedule a job that will run every day at 21:00. The job should run today if the job is started before 21:00. After 21:00 it should start tomorrow.

Thanks

**Comment by mdissel** [comment]
see #181

**Comment by tallesl** [comment]
That's indeed inconsistent. Flagging it as a bug and fixing in it on the ongoing redesign.

**Comment by VitorCioletti** [comment]
Just fixed this issue in redesign branch.  It will soon be released.

:)
