### ISSUE TITLE
Only allow one job at a time

### ISSUE THREAD

**Issue by tarockx** [fluentscheduler/FluentScheduler#201]
Is there a way to force FluentScheduler to only run one job at a time? By which I mean that if a job is already running and another one is added, the new one should only rung after the currently running one is complete.

I know the Schedule object has a `.NonReentrant()` method, but that doesn't help because it only avoids overlapping in a specific schedule. I need to only run one job at a time GLOBALLY.

Is this possible?

**Comment by tallesl** [comment]
There's no such thing and, to be honest, I see little value in adding it to the library.

You can, however, hook up your own. Like:

```cs

    using System.Threading;
public class MyJob : GlobalJob
{
    public override void Execute()
    {
        // Do work, son!
    }
}

public abstract class GlobalJob : IJob
{
    private static readonly object _globalLock = new object();

    public abstract void Execute();

    void IJob.Execute()
    {
        if (Monitor.TryEnter(_globalLock))
        {
            try
            {
                Execute();
            }
            finally
            {
                Monitor.Exit(_globalLock);
            }
        }
    }
}
```
