### ISSUE TITLE
Sequential job scheduling

### ISSUE THREAD

**Issue by gguillen** [fluentscheduler/FluentScheduler#203]
It would be great if you could schedule a job, and then have another run when the first one is complete, and then run another after the previous one was complete, etc.  That way you can enforce order on job execution.  Something like:

```csharp
Schedule<MyFirstJob>().WithName("Doing stuff here first")
    .AfterThat<MySecondJob>().WithName("Doing more stuff here")
        .AfterThan<SomeOtherJob>().WithName("Even more stuff")
    .NonReentrant()
    .ToRunNow()
    .AndEvery(5).Minutes();
```

**Comment by tallesl** [comment]
There's `AndThen`:

```cs
Schedule<MyFirstJob>().WithName("Doing stuff here first")
    .AndThen<MySecondJob>().WithName("Doing more stuff here")
    .AndThen<SomeOtherJob>().WithName("Even more stuff")
    .NonReentrant()
    .ToRunNow()
    .AndEvery(5).Minutes();
```

**Comment by gguillen** [comment]
Now I see why this did not appear to work for me before... The JobManager.JobStart is called with the JobStartInfo for the first job (MyFirstJob), and JobEndInfo is called for the last job in the chain (SomeOtherJob) but intermediary jobs (MySecondJob) do not trigger the start and stop events.
