### ISSUE TITLE
JobManager.JobStart does not fire for first job invokation

### ISSUE THREAD

**Issue by thulani-chivandikwa** [fluentscheduler/FluentScheduler#204]
On scheduling a job while subscribed to the Job events the JobStart does not fire for the first schedule, however JobEnd does. When the recurring Job triggers again then the JobStart is fired.

`private void Initialize()
        {
            JobManager.Initialize(new JobRegistry());

            JobManager.JobStart += JobManagerOnJobStart;
            JobManager.JobEnd += JobManagerOnJobEnd;
            JobManager.JobException += JobManagerOnJobException;
        }

        private void JobManagerOnJobStart(JobStartInfo jobStartInfo)
        {
        }

        private void JobManagerOnJobException(JobExceptionInfo jobExceptionInfo)
        {
        }

        private void JobManagerOnJobEnd(JobEndInfo jobEndInfo)
        {
        }

    public class ProductDataReplicationJob : IJob
    {
        public void Execute()
        {

        }

        public static string JobName => nameof(ProductDataReplicationJob);
    }

  public class JobRegistry: Registry
    {
        public JobRegistry()
        {
            NonReentrantAsDefault();

            Initialize();
        }

        private void Initialize()
        {
            Schedule<ProductDataReplicationJob>()
                .ToRunNow()
                .AndEvery(10)
                .Seconds();
        }
    }`

**Comment by tallesl** [comment]
You have a race condition.

Change:

```cs
private void Initialize()
{
    JobManager.Initialize(new JobRegistry());

    JobManager.JobStart += JobManagerOnJobStart;
    JobManager.JobEnd += JobManagerOnJobEnd;
    JobManager.JobException += JobManagerOnJobException;
}
```

To:

```cs

private void Initialize()
{
    JobManager.JobStart += JobManagerOnJobStart;
    JobManager.JobEnd += JobManagerOnJobEnd;
    JobManager.JobException += JobManagerOnJobException;

    JobManager.Initialize(new JobRegistry());
}
```
