### ISSUE TITLE
Simple schedule to run every minute on the minute rather than a minute from the current time?

### ISSUE THREAD

**Issue by echodreamz** [fluentscheduler/FluentScheduler#206]
Is it possible to setup a scheduler with Fluent that runs every minute on the minute rather than 1 minute from the time the scheduler was started? For example...

12:00:00
12:01:00
12:02:00
12:03:00
etc. etc.

Quartz can do this using Cron expressions, but Quartz is overly complex for our needs, although maybe this is why. Love Fluent and use it for a ton of things, but never something this specific.

**Comment by MarkusKgit** [comment]
You could use DelayFor() to achieve this. I hacked together a small demo console app:

```
static void Main(string[] args)
        {
            JobManager.Initialize(new Registry());
            var delayToNextFullMinute = 60 - DateTime.Now.Second;
            Console.WriteLine($"It is {DateTime.Now:HH:mm:ss}. You have to wait {delayToNextFullMinute} seconds to the next full minute");
            JobManager.AddJob(
                () => Console.WriteLine($"It is {DateTime.Now:HH:mm:ss}"),
                s => s.WithName("Every Minute")
                .ToRunEvery(1)
                .Minutes()
                .DelayFor(delayToNextFullMinute)
                .Seconds()
                );
            Console.WriteLine($"Next run is at: {JobManager.AllSchedules.Single(x => x.Name == "Every Minute").NextRun:HH:mm:ss}");
            Console.ReadLine();
        }
```
The only issue is that it seems to add another minute before it actually starts. Sample output:
```
It is 11:41:41. You have to wait 19 seconds to the next full minute
Next run is at: 11:43:00
It is 11:43:00
```
You could substract another 60 seconds from ``delayToNextFullMinute`` (making it negative) to have it start at the next full Minute.

**Comment by MarkusKgit** [comment]
Hmm I thought it might. I came up with another solution but it is really hacky and I'm not sure if it suffers from race conditions. Basically make a single Job and add it to the schedule again after you are finished:
```
private static void Main(string[] args)
        {
            JobManager.Initialize(new Registry());
            AddJob();
            Console.ReadLine();
        }

        private static void AddJob()
        {
            var now = DateTime.Now;
            JobManager.AddJob(Job,
                s => s.WithName("Every Minute")
                .ToRunOnceAt(now.Hour, now.Minute + 1)
                );
            Console.WriteLine($"Next run is at: {JobManager.AllSchedules.Single(x => x.Name == "Every Minute").NextRun:HH:mm:ss}");
        }

        private static void Job()
        {
            Console.WriteLine($"It is {DateTime.Now:HH:mm:ss}");
            //Should not need this as it is a single job
            //JobManager.RemoveJob("Every Minute");
            AddJob();
        }
```

Of course the best option would be cron. You can kind of emulate that already using reflection but again that is a hack (although it works quite well in one of my projects). Hopefully we will get proper support for cron in the future.

**Comment by tallesl** [comment]
Cron support it's on its way (#214).
