### ISSUE TITLE
Could not load file or assembly 'FluentScheduler, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference

### ISSUE THREAD

**Issue by atesoglu** [fluentscheduler/FluentScheduler#208]
Weird problem; i've a solution that has two projects, one with .netstandard 2.0 (ClassLibrary) and the other .net framework 4.6.1 (Web Application). Basically web app has reference for class library.

In class library, i'm implementing some logic for scheduled jobs and in web app, i'm calling those classes, but weirdly, i have a exception like this;

`Could not load file or assembly 'FluentScheduler, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

I've double checked the dll file is in bin folder, everything seems fine but the error doesn't go away.

Also i'm having same problem with a console application too, so any help?

Thank you in advance.

_**EDIT:**_
Ok, after reviewing the source code, i've realized that there are two seperate projects in solution targeting bot .net4.0 and a portable class library. Those different dll files are creating my issue, so i've forked the master branch and converted project to .netstandard2.0 and requested a pull request.

I think that will resolve issues like this in the future, so how about merging and release a new nuget package?

Thank you in advance.

> Hello? (hello) (hello)
Is there anybody in there?
Just nod if you can hear me
Is there anyone at home?
Come on (come on), now
I hear you're feeling down
Well I can ease your pain
And get you on your feet again
Relax
I need some information first
Just the basic facts
Can you show me where it hurts?

**Comment by tallesl** [comment]
There are issues on using the current version of the library with .NET Core (#118, #159, #208).

I think those came from the current support being a portable library thingy, made prior to core 2.0, and poorly tested by me (sorry).

I'm relunctant on making changes on the current version that lives on master, however the current library redesign (#214) is been done entirely in .NET Core.

I kindly ask you folks to wait for the redesign to be done.
