### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by BillChirico** [fluentscheduler/FluentScheduler#212]
Hello,

Is there Nuget package for the redesign? I’d like to use it in my project.

Thanks
- Bill

**Comment by VitorCioletti** [comment]
Unfortunately there is not. Redesign is meant to recreate (redesign) the library's structure.
However, we will soon merge redesign to master and publish a new package to NuGet.

Closing this issue. Feel free to reopen it. 

:)
