### ISSUE TITLE
FluentScheduler fire my own sql table data Change

### ISSUE THREAD

**Issue by vahidarr** [fluentscheduler/FluentScheduler#215]
I Have a Table in my own Sql database that I want When a Separate Service change the Table Data for example Add new Row to that Table، a trigger or job or anything Fire (base on sql table change) .I dont want check that table in a repetitive time because it is not have a good performance.we also have SqlDependency in ADO.NET but i prefer not to use it.
How can i Do That in FluentScheduler???

**Comment by tallesl** [comment]
The only thing controlling when a schedule is fired is some time constraint.

Sorry, you can't do that with the library (but it can be used for polling though).
