### ISSUE TITLE
LastWeekdayBefore and FirstWeekdayAfter

### ISSUE THREAD

**Issue by mkromkamp** [fluentscheduler/FluentScheduler#217]
# Schedule a job on the last weekday before or the first weekday after a certain date

Would be really awesome to schedule a monthly job on the last weekday before or the first weekday after that day. The main driver for an addition like this would be to schedule a job that should run around a certain date on a specific day. Wich for us developers sounds crazy but is something I encounter a lot within companies.

## How should it work

For example, I want to schedule a job on the last Thursday before the 20th of the month. So for 10/2018 that would result in scheduling it on the 18th, because the 20th is on a Saturday.

This can also be done the other way around. So we want to schedule the job on first Thursday after the 20th. So for 10/2018 that would result in the 25th.

##  How could we do it

I think this addition could be made in the `RestrictableUnitExtensions.cs` extension method and could be very close to the implementation of the `WeekdaysOnly` extension method.

`public static IDayRestrictableUnit LastWeekdayBefore(this IDayRestrictableUnit unit, DayOfWeek day);`
`public static IDayRestrictableUnit FirstWeekdayAfter(this IDayRestrictableUnit unit, DayOfWeek day);`

That would result in a interface usage like this:

`Schedule(() => Console.WriteLine("Foo")).ToRunEvery(0).Months().On(20).LastWeekdayBefore(DayOfWeek.Thursday);`
`Schedule(() => Console.WriteLine("Foo")).ToRunEvery(0).Months().On(20).FirstWeekdayAfter(DayOfWeek.Thursday);`

## Collaboration

If you are open to such a change I would be more than happy to make a proposal and/or collaborate on the change if needed. Before starting with any additions and/or changes we could discuss the direction of the implementation to avoid ending up with something you strongly disagree with.

**Comment by puf17640** [comment]
I like the idea, but I found it hard to understand the semantics of the interface change... "Run every Month on 20th first weekday after" (?)

Without having thought about implementation yet, I would suggest taking a "Run every Month on first weekday after 20th" approach.

```
(...).ToRunEvery(0).Months().FirstWeekdayAfter(DayOfWeek.Thursday).On(20)
```
(Writing it down it doesn't seem like it would make much of a difference... but I still find this easier to read)

 I will look into it later today and edit my reply! :)

**Comment by mkromkamp** [comment]
@puf17640 Thanks for your reply. Can agree with you about the solution I pitched not being really easy to read :). And I think your edit looks super nice, to be honest.

Thinks it really well "tells" the user on the interface what will happen without bloating it by chaining too many methods 👍.

**Comment by puf17640** [comment]
My week is pretty busy, but I would love to talk to you about how that might be implemented on Friday if that would fit you? :-) If you want, inbox me at: puf17640@spengergasse.at 

I don't think it would make sense to implement it in the current version obviously, but I would be more than happy to see this being available in the new version!!

**Comment by mkromkamp** [comment]
Friday sounds fine to me. What timezone are you in, to align a conversation about this.

Implementing this in the redesign sounds like the best way going forward. If needed/requested I can always make an implementation in the current version of the library. Looked at the possibility for the current version and it should not take much time there :).

Will send you an email so you have mine as well 👍

**Comment by tallesl** [comment]
See #218.
