### ISSUE TITLE
Can i name multi jobs with one name

### ISSUE THREAD

**Issue by mshami85** [fluentscheduler/FluentScheduler#221]
Hi

>    run a task every Monday, Friday and Sunday of every week

Can i name them all as one name ?? i.e

```
Schedule<MyTask>().WithName("Job1").ToRunEvery(1).Weeks().On(DayOfWeek.Monday).At(8, 30); // Note: the .At(8, 30) portion is optional - if omitted, the task will run at 12am.
Schedule<MyTask>().WithName("Job1").ToRunEvery(1).Weeks().On(DayOfWeek.Friday).At(8, 30);
Schedule<MyTask>().WithName("Job1").ToRunEvery(1).Weeks().On(DayOfWeek.Sunday).At(8, 30);
```

So i can remove them all by using  `JobManager.Remove("Job1");`
to keep other jobs working

**Comment by tallesl** [comment]
No, unfortunately, you can't. However, in the [future](https://github.com/fluentscheduler/FluentScheduler/tree/redesign), you'll able to [group schedules](https://fluentscheduler.github.io/managing-multiple-schedules/) as you please.
