### ISSUE TITLE
Add .net standard 2.0 target

### ISSUE THREAD

**Issue by ReoInMatrix** [fluentscheduler/FluentScheduler#222]
Last version of `FluentScheduler` supports .NETStandard 1.4
but according to Microsoft guidelines (https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/) it will be great to include .NET Standard 2.0 target.

**Comment by tallesl** [comment]
> [.NET Standard 1.x is distributed as a granular set of NuGet packages, which creates a large package dependency graph and results in developers downloading a lot of packages when building. Modern .NET platforms, including .NET Framework 4.6.1, UWP and Xamarin, all support .NET Standard 2.0. You should only target .NET Standard 1.x if you specifically need to target an older platform.](https://docs.microsoft.com/dotnet/standard/library-guidance/cross-platform-targeting)

Good catch. Fixing it in the new major release.

**Comment by tallesl** [comment]
See #253.
