### ISSUE TITLE
"Using it with ASP.NET" instructions don't work with .NET Core 2.1

### ISSUE THREAD

**Issue by markshep** [fluentscheduler/FluentScheduler#225]
I've just installed fluentscheduler with .NET Core 2.1 and am trying to follow the instructions in the main README.md file, however the code in the section "Using it with ASP.NET" gives the error ````The type or namespace name 'IRegisteredObject' could not be found````.  Apparently that interface is in the System.Web.Hosting namespace, but that doesn't exist in .NET Core 2.1.

Please could you update the instruction to include .NET Core 2.1?

**Comment by tallesl** [comment]
Removed the outdated instructions.

It's been a while since I last worked with ASP.NET, labeling this as help wanted.
