### ISSUE TITLE
How Can I schedule a job for 3 times a day, except sunday?

### ISSUE THREAD

**Issue by TheColonel2688** [fluentscheduler/FluentScheduler#227]
How can I do something like this? Schedule a job for 3 times a day, except Sunday

Schedule<ReportJob>().ToRunEvery(0).Days().Except(DayOfWeek.Sunday).At(06, 30).AndAt(14, 30).AndAt(22, 30);

Maybe this should be a feature request?

**Comment by VitorCioletti** [comment]
Hi,
I guess there is no native support in the current API to do what you want. If you need a quick solution (and I know it is a messy one), run 3 schedules only on week days and the other 3 on saturday. 

The current version of the library [will be deprecated by redesign branch](https://github.com/fluentscheduler/FluentScheduler/issues/214), so there will be no new features on it. 
I liked `Except(DayOfWeek)` idea, and I believe `AndAt(int)` could be implemented by a new overload to `At`: `At(IEnumerable<TimeSpan>)`, so there is no need to call `AndAt(int, int)` over and over again.

The newest version could be that simple: 
```cs
run.Every().Day().Except(DayOfWeek.Sunday).At(myTimeSpanList))
```
@tallesl what do you think of these schedules?

**Comment by TheColonel2688** [comment]
Hi VitorCioletti,

That seems like a great syntax

**Comment by tallesl** [comment]
> run.Every().Day().Except(DayOfWeek.Sunday).At(myTimeSpanList)

A-OK with me.

Consider accepting `params IEnumerable<DayOfWeek>` and `params IEnumerable<TimeSpan>` on those.

**Comment by VitorCioletti** [comment]
See #214 for release info.
