### ISSUE TITLE
Stop, change, add new ?

### ISSUE THREAD

**Issue by oguzhansari** [fluentscheduler/FluentScheduler#231]
Hi,

This is my timer table in my database.
![image](https://user-images.githubusercontent.com/13555457/52918839-02700d00-330d-11e9-8e2a-e225739fee80.png)

That's the code I added the timer to.
`Schedule(() => new ExpiredContentNotificationJobForLead(item)).ToRunOnceAt((DateTime)item.ScheduleDate);`

I want to do;
1 - Recalibrate the timer according to this date when the date in the database changes.
2 - Set a new timer when recording is added to the database.
3 - Stop and restart the timer.

I would like you to share sample code that I can do.
(Sorry, English may be bad. I'm using Google translate.)

**Comment by tallesl** [comment]
Storing schedules are not supported. See #68.
