### ISSUE TITLE
Print scheduling for specific Job for next n occurrences 

### ISSUE THREAD

**Issue by nicolasppelis** [fluentscheduler/FluentScheduler#232]
I was wondering if there exist any function that will allow me to get next _**n**_ scheduled events.
For instance 
`JobManager.AddJob(() => Console.WriteLine($"evnt1 @ {DateTime.Now }"), (s) => s.WithName("evnt1").ToRunEvery(15).Seconds());`
`JobManager.GetNextOcc("evnt1",5)`; or even `JobManager.GetSchedule("evnt1",5); `

**Comment by tallesl** [comment]
There isn't, sorry.
