### ISSUE TITLE
Running on multiple servers

### ISSUE THREAD

**Issue by DotNetRockStar** [fluentscheduler/FluentScheduler#233]
Hi there. I was just digging around the web for something that I might be able to use to schedule jobs on an application deployed to N number of different machines. I want them all to have the scheduler running, but I only want one of them to execute the job. Is this something that the software can do? If so, does it require a database?

Thanks in advance
 - Jerrod

**Comment by VitorCioletti** [comment]
Jerrod, hi.
 
FluentScheduler does not have any feature to support such application. There are some ways to develop what you can do but this library can only help on the matter scheduling your jobs, no databases or distributed systems support (and such features are not even in the planning of the [newest version of the library](#214).

Closing this issue, feel free to reopen it.

Thanks.

**Comment by nytokyr** [comment]
Hi,
does FluentScheduler  support running on multiple machines now (2021) ?
