### ISSUE TITLE
Use a cron string for scheduling exception

### ISSUE THREAD

**Issue by pwen090** [fluentscheduler/FluentScheduler#238]
#214 I mentioned using a cron string to add exclusion support. I understand that cron itself does not have that. What I was asking is if there could be support to use a cron string but as a not.

That is to say I could have two properties like IncludeCron and ExcludeCron and they would both accept a cron string. It would make my task run during anything in the Include but not run during anything in the Exclude.

**Comment by tallesl** [comment]
Exclusion doesn’t make sense. The library doesn’t calculate when the schedule will be running, it calculates when the schedule will be fired.

Inclusion does make sense, but I’m passing for now.

What I said applies to both cron and no-cron schedules by the way.
