### ISSUE TITLE
How to run a task on a time interval that is aligned with a specific time?

### ISSUE THREAD

**Issue by thomasd3** [fluentscheduler/FluentScheduler#241]
I would like to run tasks every 5 minutes, but aligned on the hour:

1h00
1h05
1h10
.. etc

what would be the syntax for this?

**Comment by thomasd3** [comment]
would something like this work?

Startup.Scheduler.Schedule(T).ToRunEvery(IntervalTime.Seconds / (3600 * 24)).Days().At(0, 0);

and setting the interval to 5*60 = 300 seconds?

**Comment by MarkusKgit** [comment]
Have a look at #206
