### ISSUE TITLE
Confused about the API

### ISSUE THREAD

**Issue by thomasd3** [fluentscheduler/FluentScheduler#242]
If I initialize the system like this:

			var Scheduler = new Registry();
			Scheduler.NonReentrantAsDefault();
			JobManager.Initialize(Scheduler);
			JobManager.UseUtcTime();

this will run..
```
		JobManager.AddJob(
                       () => Console.WriteLine(DateTime.Now),
                       _ => _.ToRunEvery(5).Seconds()
                   );


```

this will not run:
```
                // test is a class printing time, like above, derived from IJob
		var T = new test();
		Scheduler.Schedule(T).ToRunEvery(5).Seconds();
```

Why is the second one not running?

does it mean all the jobs in the scheduler need to be registered before the job manager is started?

**Comment by tallesl** [comment]
The registry is used only on JobManager initialization, the library doesn't track any new schedules added to it afterwards. That's why `JobManager.AddJob` exists.

It's confusing, I know. It'll be fixed on the next major release (registry will be gone entirely).
