### ISSUE TITLE
Run every,but have a few days is not work

### ISSUE THREAD

**Issue by seizeMiss** [fluentscheduler/FluentScheduler#244]
I use FlentScheduler to run a program once a day, but sometimes does not execute.Has anyone encountered such a problem?How to solve this? Thank you ！

**Comment by VitorCioletti** [comment]
Maybe your job is silently crashing. `JobManager.JobException` event might help you figure that out.

**Comment by seizeMiss** [comment]
> Maybe your job is silently crashing. `JobManager.JobException` event might help you figure that out.
I used FluentScheduler for the first time,I don't know where to put `JobManager.JobException` 
1.method Application_Start()
2.the class of extend Registry

**Comment by VitorCioletti** [comment]
It would be easier if you provide me the source code. 

Anyway, you can assign a function to `JobManager.JobException` anywhere you want since it runs before `JobManager.Initialize`.

A simple sample from the official docs:

```cs
JobManager.JobException += info => Log.Fatal("An error just happened with a scheduled job: " + info.Exception);
```

**Comment by seizeMiss** [comment]
> It would be easier if you provide me the source code.
> 
> Anyway, you can assign a function to `JobManager.JobException` anywhere you want since it runs before `JobManager.Initialize`.
> 
> A simple sample from the official docs:
> 
> ```cs
> JobManager.JobException += info => Log.Fatal("An error just happened with a scheduled job: " + info.Exception);
> ```

Thank you! I look up some online information and learned about it

**Comment by VitorCioletti** [comment]
Nice! :)

Closing this issue, feel free to reopen it.

**Comment by seizeMiss** [comment]
> Nice! :)
> 
> Closing this issue, feel free to reopen it.

Some time ago, I was testing on the server, but there was still no execution, no exceptions were caught, log information was printed, and it seems that the number of non-executions has increased. What is going on?
My code is as follows：
`JobManager.JobException += info =>
            {
                Log.Error(typeof(MvcApplication).ToString(),"Error occurred in job: " + info.Name + ",e=" + info.Exception);
            };
            JobManager.Initialize(new XxxScheduler());`

**Comment by VitorCioletti** [comment]
That is weird. Could you provide the schedule source code?

**Comment by seizeMiss** [comment]
> That is weird. Could you provide the schedule source code?
suorce code:
```
public class GameCodeSizeStatisticsScheduler : Registry
    {
        public GameCodeSizeStatisticsScheduler()
        {
            // 每天凌晨5.00执行
            Schedule<CodeSizeStatisticsJob>().ToRunEvery(1).Days()
                .At(Convert.ToInt32(ConfigurationManager.AppSettings["StatisticsCodeSizeHour"]),
                    Convert.ToInt32(ConfigurationManager.AppSettings["StatisticsCodeSizeMinute"]));
        }
    }
```

**Comment by tallesl** [comment]
Is there a pattern of when this happens? Can you provide the source for `CodeSizeStatisticsJob`?

Also, are you sure the machine isn't sleeping?

I'm closing the issue since it's been a while (sorry about that), but feel free to reopen it.
