### ISSUE TITLE
Run first day, next day is not run if i can not access the site.

### ISSUE THREAD

**Issue by akbarbd** [fluentscheduler/FluentScheduler#252]
// Start up Configuration  
public void ConfigureServices(IServiceCollection services)
        {
   JobManager.Initialize(new JobRegistry(services.BuildServiceProvider().GetRequiredService<IEmailSenderService>()));
}

// My JOb Registry
 public class JobRegistry : Registry
    {

        public JobRegistry(IEmailSenderService emailSenderService)
        {
   Schedule(new AOPCostSummeryJob(emailSenderService)).ToRunEvery(1).Days().At(Aophour,AopMin);
       }
}

// Execution Function
 public class AOPCostSummeryJob : IJob
    {

        private IEmailSenderService _emailSender;

        public AOPCostSummeryJob(IEmailSenderService _emailSender)
        {
            this._emailSender = _emailSender;
        }

        public void Execute()
        {
}
}
|

**Comment by VitorCioletti** [comment]
Sorry, but I did not understand what you mean.

**Comment by tallesl** [comment]
Me neither.
