### ISSUE TITLE
How to cehck is job running or not?

### ISSUE THREAD

**Issue by Aleksej-Shherbak** [fluentscheduler/FluentScheduler#257]
How to cehck is job running or not? I have the following code in the `Startup.cs` class for initializing my job: 

    var registry = new Registry();
    registry.Schedule<SendPushesJob>().ToRunNow().AndEvery(60).Seconds();
    JobManager.Initialize(registry);

and the following code in my controller: 
    
    public IActionResult StopSender()
    {
        JobManager.Stop();
        
        return RedirectToAction("Index");
    }
    
    public IActionResult StartSender()
    {
        JobManager.Start();

        return RedirectToAction("Index");
    }

I would like to show on the view is my job started or not. How I can do this? I can't see the suitable method. 

  [1]: https://github.com/fluentscheduler/FluentScheduler

**Comment by insanity13** [comment]
As an option, you can Subscribe to Jobs Event and keep a list of running tasks manually. 
`
JobManager.JobStart
JobManager.JobEnd
JobManager.JobException
`

**Comment by Aleksej-Shherbak** [comment]
@insanity13 but it's not very convenient( Or I don't understand you. 

Right now I have only one job for whole project, so I can check whether it works like 

                    <span>
                        @if (JobManager.AllSchedules.Any())
                        {
                            <strong class="text-success">Working</strong>   
                        }
                        else
                        {
                            <strong>Not working</strong>   
                        }
                    </span>

After some tests I have understood the following. I can't stop or start particular job. I can stop or start whole jobs via `JobManager` with the help of commands `JobManager.Stop()` or `JobManager.Start()`. To stop or start only one job I have to remove it or add it again. Am I right? I see ability to remove a job by name. But how to set name for job? While I have only one job for whole project it's not important for me, but if I want to have several jobs, I will have problem. So, my code for start and stop is: 

    public IActionResult StopSender()
    {
        JobManager.RemoveAllJobs();
        
        return RedirectToAction("Index");
    }
    
    public IActionResult StartSender()
    {
        JobManager.RemoveAllJobs();

        var registry = new Registry();
        registry.Schedule<SendPushesJob>().ToRunNow().AndEvery(60).Seconds();
        JobManager.Initialize(registry);

        return RedirectToAction("Index");
    }
 
This code explains the problem with setting name for job: 

        public IActionResult StopSender()
        {
            // JobManager.RemoveAllJobs();
            
            JobManager.RemoveJob("how to set this name???");
            
            return RedirectToAction("Index");
        }
        
        public IActionResult StartSender()
        {
            JobManager.RemoveAllJobs();

            var registry = new Registry();
            var schedule = registry.Schedule<SendPushesJob>();
            schedule.Name = "name is inaccessible"; // name is inaccessible ((( 
            var secondUnit =  schedule.ToRunNow().AndEvery(60).Seconds();
            JobManager.Initialize(registry);

            return RedirectToAction("Index");
        }
    }

Unfortunately I can't  understand this part of functional. It would be nice, if author update `redme.md`

**Comment by Aleksej-Shherbak** [comment]
So, after some tests I have understood that I can't stop or start particular job. Instead, I can remove or add job via `JobManager.Stop()` or `JobManager.Start()`. 

So here is the code.

Start and stop: 

    public IActionResult StopSender()
    {
        JobManager.RemoveJob("push_distribution");
        
        return RedirectToAction("Index");
    }
    
    public IActionResult StartSender()
    {
        JobManager.RemoveJob("push_distribution");

        var registry = new Registry();
        registry.Schedule<SendPushesJob>().WithName("push_distribution").ToRunNow().AndEvery(60).Seconds();

        JobManager.Initialize(registry);

        return RedirectToAction("Index");
    }

Show if the job is running:  

    <span>
        @if (JobManager.AllSchedules.Any(x => x.Name == "push_distribution"))
        {
            <strong class="text-success">Working!</strong>   
        }
        else
        {
            <strong>Not working!</strong>   
        }
    </span>

Is it correct way?

**Comment by tallesl** [comment]
That seems to be correct. It's embarrassingly cumbersome doing that in the current version, and it shouldn't.

We'll be fixing that on 6.0.0, see #273.
