### ISSUE TITLE
How to use DI? 

### ISSUE THREAD

**Issue by Aleksej-Shherbak** [fluentscheduler/FluentScheduler#259]
In readme.md I have seen that `IJobFactory` is depricated. How to use DI for the library?

**Comment by MelbourneDeveloper** [comment]
@Aleksej-Shherbak mint your Job with dependency injection (e.g. with ServiceProvider). 

Then, pass it in to the `Schedule` method.

The trick is that you have to pass the job in as an argument, not let the Schedule method construct the job for you. You can also use a Func to construct the job if it makes you feel better.

**Comment by tallesl** [comment]
I'm closing the issue, but feel free to keep the conversation going on #271.
