### ISSUE TITLE
Add .Between(TimeSpan, TimeSpan) and .Every(TimeSpan)

### ISSUE THREAD

**Issue by grschtroumpf** [fluentscheduler/FluentScheduler#260]
Hello, 

First of all, great project!!   :)
Maybe I missunderstand the UnitTests but I don't see a way to do something like this:

schedule.ToRunEvery(1).Weeks().On(DayOfWeek.Monday).Between(new TimeSpan(10, 00, 00), new TimeSpan(11, 00, 00)).Every(new TimeSpan(00, 05, 00);

So basically, I would like to run:
- every week
- on Monday (and some other days of the week)
- between 10 AM and 11 AM
- every 5 minutes

Is it possible with the current implementation?

**Comment by tallesl** [comment]
Hey, thanks!

You can't do it on the current version ([master](https://github.com/fluentscheduler/FluentScheduler/tree/master) branch).

However, I believe it's possible on the current 6.0.0-alpha ([redesign](https://github.com/fluentscheduler/FluentScheduler/tree/redesign) branch). See #273.

**Comment by tallesl** [comment]
Edit: Sorry, you can't :(
