### ISSUE TITLE
ActiveX controls and FluentScheduler throws an exception

### ISSUE THREAD

**Issue by ricpersi** [fluentscheduler/FluentScheduler#262]
Trying to schedule a job which loads an ActiveX Objects I get:
ActiveX control [ActiveX Object] cannot be instantiated because the current thread is not in a single-threaded apartment

I found a similar question on S.O.:

https://stackoverflow.com/questions/55374569/how-use-fluentscheduler-with-activex-in-single-threaded-apartment

Any advice on this?

**Comment by tallesl** [comment]
Sorry for the trouble, but do you mind commenting on #272?

Thanks!
