### ISSUE TITLE
FluentScheduler Status Update?

### ISSUE THREAD

**Issue by brianjlacy** [fluentscheduler/FluentScheduler#266]
@tallesl Are you still working on this project?

I'm very interested in the redesign, but it looks like it hasn't been updated for awhile now and issues seem to be stacking up a bit. I won't use the _D_-word, but...

_P.S. I know (all too well) how other things in life take priority over projects like this!_ Just curious to know where things stand! Thanks.

**Comment by tallesl** [comment]
Yes, I'm still working on it.
