### ISSUE TITLE
Saving jobs to persistent storage

### ISSUE THREAD

**Issue by jdahan91** [fluentscheduler/FluentScheduler#269]
Seems like the author of this library isn't active here anymore nor pushing updates. So I don't know if opening here feature requests is useless or not, but I'm going to ask anyways.

I would like to see an option to let FluentScheduler save ongoing jobs to disk (some sort of a db) and reload them upon restart of the application. 

Hangfire has this feature but I really don't want to migrate to Hangfire because of the complexity of Cron usage whereas FluentScheduler has simplicity.

**Comment by tallesl** [comment]
>Seems like the author of this library isn't active here anymore nor pushing updates.

Hey, I'm here.

> whereas FluentScheduler has simplicity

Precisely. And that's why we won't support it.

[Quoting myself](https://github.com/fluentscheduler/FluentScheduler/issues/68#issuecomment-417963852):

> I'm against bloating the library with features. I prefer to do 2 things well than a 100 poorly. I'm not aiming to rival Quartz.NET or Hangfire in number of features.
