### ISSUE TITLE
Snap/window schedule time?

### ISSUE THREAD

**Issue by avanderhoorn** [fluentscheduler/FluentScheduler#276]
I'm wanting to run a task every 5min on the 5min of the of the hour regardless of when the app starts... i.e. app starts at 12:02:35, it would either run immediately or wait (depending on config), and then run at 12:05, 12:10, 12:15, etc. Anyone know how to achieve this setup?

**Comment by kvpt** [comment]
I also have this requirement.

This is my solution.

I first made an extension method for the rounding
```cs
 public static DateTime RoundUp(this DateTime date, TimeSpan interval)
 {
      return new DateTime((date.Ticks + interval.Ticks - 1) / interval.Ticks * interval.Ticks, date.Kind);
 }
```

And we use it like this
```cs
     ...
        .ToRunOnceAt(DateTime.Now.RoundUp(TimeSpan.FromMinutes(5)))
        .AndEvery(5)
        .Minutes()
```

**Comment by tallesl** [comment]
Next version will support it through cron expressions, but you can't do it with the current one.

Thank you so much for the provided snippet, @kvpt.
