### ISSUE TITLE
Reentrant or non-reentrant?

### ISSUE THREAD

**Issue by richard-browne** [fluentscheduler/FluentScheduler#284]
I'm confused about whether the default for a schedule is reentrant or non-reentrant. This page says the default is non-reentrant:

https://fluentscheduler.github.io/reentrancy/

But here it says the opposite:

https://github.com/fluentscheduler/FluentScheduler#concurrent-jobs

Which is correct?

**Comment by VitorCioletti** [comment]
Consider the second link because the first one is from the alpha (6.0.0) version.

**Comment by richard-browne** [comment]
Thank-you for the reply. So if I understand this is a change in default for the upcoming V6? If so it's a pretty big change IMO.

**Comment by VitorCioletti** [comment]
This library was completely rewritten in the newest version. See #214.

**Comment by richard-browne** [comment]
No worries. Just some feedback from a casual user who isn't following the development. If I upgraded from V5 to V6 when it's released I wouldn't expect such a fundamental change in behaviour. Now I know. All good and thank-you for the replies.

**Comment by richard-browne** [comment]
Also if I could make the point.. I landed on that page https://fluentscheduler.github.io/reentrancy via google, there's nothing to tell me this info is for an upcoming alpha release and doesn't apply to the current shipping release.

**Comment by VitorCioletti** [comment]
> No worries. Just some feedback from a casual user who isn't following the development. If I upgraded from V5 to V6 when it's released I wouldn't expect such a fundamental change in behaviour. Now I know. All good and thank-you for the replies.

You should expect fundamental changes in any API when a new major version comes out because it means a backwards incompatibility in some degree. 

> Also if I could make the point.. I landed on that page https://fluentscheduler.github.io/reentrancy via google, there's nothing to tell me this info is for an upcoming alpha release and doesn't apply to the current shipping release.

This was an error and I agree with you that is quite confusing, we are probably going to add the version somewhere to prevent it. Thanks for helping it out.

**Comment by tallesl** [comment]
Originally I was 'saving' fluentscheduler.github.io for version 6  but it seems Google ended up indexing it. I just changed it to reflect the current version 5, sorry for the confusion.
