### ISSUE TITLE
how to use in .Net Framework4.~?

### ISSUE THREAD

**Issue by lovh** [fluentscheduler/FluentScheduler#292]
hello 
have 1 question, 
can i use in .Net Framework4.5?, 4.51?, 4.6?, 4.62? other versions in 4.~
but this lib use version netstandars, how to use in 4.~?

**Comment by orochasamuel** [comment]
Hi @lovh.

I use normally with windows forms application and .net 4.7.2.

Try install and use :)

**Comment by TimzChen** [comment]
Maybe you can use the previous version:  https://www.nuget.org/packages/FluentScheduler/5.3.0

**Comment by tallesl** [comment]
Previous version is the way to go. If assistance is still needed please post here and will reopen it.
