### ISSUE TITLE
How to run a job every 15 minutes at 00, 15, 30, 45

### ISSUE THREAD

**Issue by richard-browne** [fluentscheduler/FluentScheduler#302]
Sorry for a dumb question. What is the best way to run a task every 15 minutes starting on the hour - 00, 15, 30, 45 - and keep executing 24x7? Is it the following?

Schedule<MyJob>().ToRunEvery(15).Minutes().Between(0, 0, 23, 59);

It's not clear to me if that does what I want or if there is a more obvious way. Thank-you for your help.

**Comment by ozantopal** [comment]
I don't know whether this issue still active or not. Maybe too there's a better practice but you can do solve your problem with that: 

``` 
JobManager.Initialize();
JobManager.AddJob(
    () => { Console.WriteLine("The time is {0:HH:mm:ss}", DateTime.Now); },
    s => s.ToRunOnceAt(new DateTime(
        year: DateTime.Now.Year,
        month: DateTime.Now.Month,
        day: DateTime.Now.Day,
        hour: DateTime.Now.Hour,
        minute: DateTime.Now.AddMinutes(15 - (DateTime.Now.Minute % 15)).Minute,
        second: 0))
        AndEvery(15).Minutes());
```

**Comment by echodreamz** [comment]
This works for a bit, but after a while, it becomes out of sync and tasks and tasks are not executing on 00:00:00 or 00:15:00 etc. It starts executing at 00:00:07 or 00:15:07.

It seems the milliseconds are not being set to 0 and they start adding up, pushing the AndEvery(x).Minutes() further out.

**Comment by richard-browne** [comment]
Thanks for the replies. Since I asked this question I learnt it is not possible with FluentScheduler <= V5. From what I read V6 when it is released will make it possible with cron expressions.
