### ISSUE TITLE
ASP.NET 5

### ISSUE THREAD

**Issue by jasonlaw** [fluentscheduler/FluentScheduler#304]
Hi,

Can this be used in ASP.NET 5? Any additional configuration required for that?

Thanks!

**Comment by akshay-zz** [comment]
I'm using it in ASP .net 5. Didn't found any issue with that.

**Comment by jasonlaw** [comment]
Hi @akshay-zz ,

Thanks for the info, it is great to know that this can be used with ASP .NET 5 without any issue, thanks again.

My concern was triggered by [this (ASP.NET)](https://github.com/fluentscheduler/FluentScheduler/tree/006717f56771d62c4b2766c24ce2b0f531e48b86#using-it-with-aspnet)
 actually, thought this need to be taken care as well for ASP.NET 5.

**Comment by ptjuanramos** [comment]
> My concern was triggered by [this (ASP.NET)](https://github.com/fluentscheduler/FluentScheduler/tree/006717f56771d62c4b2766c24ce2b0f531e48b86#using-it-with-aspnet)

Either way I guess that, the feature that you mentioned will not work properly with the older .NET core.
I think that you would still need to use the proper [replacement method](https://stackoverflow.com/a/42785667/8477631)

**Comment by jasonlaw** [comment]
Thanks @ptjuanramos for the info.
One question, instead of handling it in each job (as per the old ASP.NET way), would that be make sense if we just call the JobManager.Stop when the application is stopping?

**Comment by ptjuanramos** [comment]
> would that be make sense if we just call the JobManager.Stop

I guess so. My feeling is that, in order to use [ `JobManager.Stop()`](https://fluentscheduler.github.io/starting-and-stopping/) you need to keep your schedule jobs in your [Registry](https://fluentscheduler.github.io/creating-schedules/)

**Comment by jasonlaw** [comment]
Understood. Thank you very much, really appreciate it!
