### ISSUE TITLE
[Bug] ToRunOnceIn stuck in a loop

### ISSUE THREAD

**Issue by ghost** [fluentscheduler/FluentScheduler#306]
Hi, instantiating a class which inherits from `Registry` and implements `IJob`, I'm scheduling `Execute` method in _ctor_ to `RunOnceIn(1).Seconds()`.

Inside the `Execute` method there's a condition where I call `Schedule(Execute).Disable()` and raise an **event**. Inside the event handler I then go through a flow which raises another event and inside that event handler I call `JobManager.Initialize()` on the class I've instantiated in the beginning. When this happens, the `Execute` method goes into a loop which runs every second instead once within a second.

Note that i'm scheduling `Execute` to run `OnceIn(1).Seconds` and another `AndEvery(10).Seconds()` which means after 10 seconds the behaviour is gone and gets back to normal.

Please fix this bug ASAP as i'm using this code in production. Awaiting a fix, thank you.

Edit - An example code looks like this:

```
Schedule(Execute).ToRunOnceIn(1).Seconds();
Schedule(Execute).ToRunEvery(10).Seconds();
```

**Comment by dahanj95** [comment]
I'm sorry, my bad. It's not a bug in the library it's just me misusing the library. Instead of Stopping the active jobs i'm calling registering to the Registry a call to .Disable() on Execute which does nothing because it's conflicting with Initialize of JobManager call.
