### ISSUE TITLE
Provide a dashboard

### ISSUE THREAD

**Issue by tkggusraqk** [fluentscheduler/FluentScheduler#309]
Provide a dashboard, such as hangfire. This allows more free control tasks, which can be invoked and executed at any time.

**Comment by DonkeyKongJr** [comment]
Latest update on the repo was over a year ago, not sure if there will be anything actively developed.

**Comment by ptjuanramos** [comment]
Probably this should be treated as a new project?

**Comment by tallesl** [comment]
> Provide a dashboard, such as hangfire

Is there anything that hangfire doesn't do or doesn't do well? In other words, what could we do differently?

> not sure if there will be anything actively developed

Slowly coming back here

> Probably this should be treated as a new project?

Yes, and there's plenty open issues here... if anyone is interest on building a separate package on top of FluentScheduler I'm all in for it (and will help out), but I'll avoid take this on my own for now
