### ISSUE TITLE
How to schedule a one-off event at run-time?

### ISSUE THREAD

**Issue by jackfox10** [fluentscheduler/FluentScheduler#314]
Ok I know this is against the idea of using a scheduler but what if I have a use case where I want to schedule a job every x minutes but also when an event happens?

An example would be refreshing data every five minutes but also refreshing data when a user clicks a button for example.

As far as I know there this would not work:
```
registry.Schedule<MyJob>().ToRunEvery(5).Minutes();
onEventFired(() => registry.Schedule<MyJob>().ToRunNow());
```

But is there a way to get the scheduler to run the job as a one off?

I could of course just run the code from within onEventFired without the scheduler but I would be worried about thread safety in this case and would prefer to use the scheduler.

Thanks!

**Comment by ghost** [comment]
Inside the event handler just call `JobManager.AddJob` directly without having to schedule a `Registry` class. When you schedule a `Registry` you have to call `JobManager.Initialize`.

**Comment by mrgfisher** [comment]
Another option @jackfox10  ...

I've use the scheduler as thin as possible in the job defnition. Effectively all it does it fire of a command using the mediatr library (https://github.com/jbogard/MediatR) with the implementation in some other assembly. Then I've referenced the same assembly from whereever I can respond the user event and that too fires of a command. The handler then 'does its thing' caring not if its scheduled or user drive. i.e it's more about seperating the concerns into three - schedule a command, respond to user event with command, act on command.

Hope that makes some sense 😊

**Comment by tallesl** [comment]
> I know this is against the idea of using a scheduler

You stole my answer on the question itself!

In all seriousness: just call your code? FluentScheduler is trying to abstract away the scheduling for you, and not necessary the 'managing of the jobs' if that makes sense.
