### ISSUE TITLE
[Bug] Accuracy problem

### ISSUE THREAD

**Issue by ghost** [fluentscheduler/FluentScheduler#327]
I tested the library there's an accuracy problem with the time the Execute method gets called. For example, if i schedule to run Now and Every 5 seconds, the Execute method will get fired after a second or three instead of 5 seconds. If I schedule after 55 minutes it will get executed after 54 minutes and sometimes 54 minutes and 56 seconds.

**Comment by ExtraTNT** [comment]
i have a pr open, which could fix your problem (as a side effect, is a fix for something else...) you can try it...
