### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [fluentscheduler/FluentScheduler#330]
Maybe You will be interested in hosting API Explorer online:
https://dndocs.com/d/fluentscheduler/api/FluentScheduler.html

This is ready-to-go, so above link can be added to README.md for other people to see it.
Or using ready shields.io badge:

[![Static Badge](https://img.shields.io/badge/API%20Docs-DNDocs-190088?logo=readme&logoColor=white)](https://dndocs.com/d/fluentscheduler/api/FluentScheduler.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Docs-DNDocs-190088?logo=readme&logoColor=white)](https://dndocs.com/d/fluentscheduler/api/FluentScheduler.html)
```

https://github.com/NeuroXiq/RobiniaDocs

Regards
NeuroXiq

**Comment by tallesl** [comment]
Getting to this late here, I'm getting 404 for your robinia docs thing...

Are you still supporting it? Do you want us to help out with your effort? Kindly reply here if there is still interest and I'll help out

**Comment by NeuroXiq** [comment]
Are you still supporting it -> Yes
Short story; DNDocs allows to host API documentation.
For example: 
[![Static Badge](https://img.shields.io/badge/API%20Docs-DNDocs-190088?logo=readme&logoColor=white)](https://docs.dndocs.com/n/FluentScheduler/5.5.1/api/FluentScheduler.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Docs-DNDocs-190088?logo=readme&logoColor=white)](https://docs.dndocs.com/n/FluentScheduler/5.5.1/api/FluentScheduler.html)
```
If You find this useful I can add this badge to README.md file to allow other people to explore API Docs of the project. 
Basically thats all :)
