### ISSUE TITLE
Add a Release<T>(T instance) method to ITaskFactory and call it when the task finishes.

### ISSUE THREAD

**Issue by hessj001** [fluentscheduler/FluentScheduler#38]
I might be missing something but GetInstance<T> is called every time the ITask Execute which is great.  The problem is that if the ITask is set to not be a singleton in the IoC container then I start leaking ITasks.  My suggestion is to add a ReleaseInstance<T>(T) method to ITaskFactory and call it after the ITask.Execute method has finished.

**Comment by mdissel** [comment]
Or just check if the taks implement IDisposable and automatically dispose the task after running.

**Comment by tallesl** [comment]
@hessj001, @dnauck 

By leaking you mean a "true leak" (your jobs holds unmanaged resources) or a "false leak" (there's no unmanaged resources involved but the library is holding up your instances and they never get garbage collected)?

If it's an actual leak it's just a matter of implementing a check on the library for jobs that implement [`IDisposable`] and dispose it just as @mdissel suggested (you should dispose whatever you need to dispose on your [`Dispose`]). Should be easy to implement.

(Implementing a `ReleaseInstance` as you suggested would solve it, but wouldn't be as idiomatic).

But if you're afraid that the library is holding up unused references of your jobs I wouldn't worry much, taking a quick glance on the code it seems to be OK. If you're still afraid of it I can set up a quick test and analyze a memory dump (don't be shy to ask!).

[`IDisposable`]: https://msdn.microsoft.com/library/System.IDisposable
[`Dispose`]: https://msdn.microsoft.com/library/System.IDisposable.Dispose
