### ISSUE TITLE
ToRunOnceAt execute task even given spesific date is allready past

### ISSUE THREAD

**Issue by YakupIpek** [fluentscheduler/FluentScheduler#52]
I belive ToRunOnceAt shouldn't execute already specific dates which is already overdue.
Here is example

```c#
TaskManager.AddTask(() => { throw new Exception("overdue task"); }, sc => sc.ToRunOnceAt(DateTime.Now.AddSeconds(-1)));
```

**Comment by jgeurts** [comment]
Is there a realistic scenario for this being an issue?

**Comment by YakupIpek** [comment]
I am saving schedule settings in database and insert them into TaskManager when the site initialized. So i see that some of the specific dated schedules already passed. I can handle by not inserting to TaskManager but i believe that it would be better design to ignore overdue task.

**Comment by tallesl** [comment]
I would argue that the way it is now is a better design.

Think about someone configuring (in some sort of configuration file/database) a date and time for a schedule to run. It's not impossible imagining them taking a look at their wristwatch and setting a time. But now imagine that there are  difference between their time and the server (few minutes). At first glance they might not realize that such difference exists, and debugging until finding it out why the task didn't start wouldn't be fun.

But being more realistic, not starting overdue tasks may raise some challenges on FluentScheduler itself. From the time you set a task to run "right now" and when FluentScheduler will actually run there's a tiny window of time (milliseconds, but still). Nothing is instantaneous.

In your case specifically I suggest you to take out from the database the tasks that are pending to run (a retrieval followed by a delete). That's a better design (IMO), you not only avoiding to wrongfully running the task again but you also have in your database the precise information of what is pending to run.

I'm closing this issue but feel free to bump it.
