### ISSUE TITLE
Schedule task to run only during peak hours

### ISSUE THREAD

**Issue by klaasdevoghel** [fluentscheduler/FluentScheduler#58]
Hello
is it possible to schedule a task hourly, but only during peak hours (eg: from 8AM until 5 PM)
It would be nice if we would keep this logic out of the task functionality.

And also: to run a task hourly, but not during the weekend.

Thanks in advance
Klaas

**Comment by jgeurts** [comment]
Seems reasonable

**Comment by 9swampy** [comment]
This sounds very similar to my requirement. I've coded and submitted a WeekDays pull request (https://github.com/fluentscheduler/FluentScheduler/pull/60); did you (@klaasdevoghel) make any progress on implementing the "during peak hours" bit?

**Comment by 9swampy** [comment]
Nvm, I've updated my prior pull request to include an implementation of this too. Happy to take feedback :)

**Comment by klaasdevoghel** [comment]
Thanks for the update, @9swampy.   I didn't make any code changes yet.  Maybe I'll have a look at your implementation in the near future.

**Comment by tallesl** [comment]
@klaasdevoghel, we just finished 4.0.0 which includes @9swampy pull request.

Right now it's just here on GitHub ([you can download the nupkg on the release page](https://github.com/fluentscheduler/FluentScheduler/releases/tag/4.0.0)), but in a couple of days it's going to nuget.org.

Sorry for the long delay!
