### ISSUE TITLE
Seeking New Ownership!

### ISSUE THREAD

**Issue by jgeurts** [fluentscheduler/FluentScheduler#59]
Would anyone like to take over ownership of this project? I have moved on from .net and do not intend to maintain this library. If you're interested, please respond to this issue.

**Comment by tallesl** [comment]
Hey Jim,

I've being using FluentScheduler for some months and it's been great so far.

I'm willing to take the role if you are unable to do it anymore.
I'm a .NET developer from 9 to 5, I do C# all day long; plus the code seems to be easy to grasp.

p.s.: one thing I would like to (try to) do it's to get around the [HostingEnvironment boilerplate](4) (without adding the System.Web reference ofc). Maybe some reflection magic does the trick.

**Comment by jgeurts** [comment]
Thanks! Please reach out if I can do anything!

**Comment by HakanL** [comment]
I'm interested in helping out too if you need additional help.
