### ISSUE TITLE
Quarterly Task 

### ISSUE THREAD

**Issue by NileshMoradiya** [fluentscheduler/FluentScheduler#64]
What to do when i wants to run any task on any quarter starts ?

**Comment by tallesl** [comment]
Hi Nilesh, sorry for the long delay!

To run every 3 months it's just a matter of setting `.ToRunEvery(3).Months()`.

If you want to start from January 1st, you can do as below instead:

```cs
TaskManager.AddTask(
    () => { /* your task */ },
    x => x.ToRunAt(DateTime.Today.FirstOfYear()).AndEvery(3).Months()
);
```

I'm closing the issue but feel free to comment further or ask to reopen.
