### ISSUE TITLE
Support task custom arguments

### ISSUE THREAD

**Issue by aijorgenson** [fluentscheduler/FluentScheduler#65]
I want to dynamically schedule a task with custom arguments.

I was hoping I could do something like below:
```C#
    CustomTask myTask= new CustomTask ();
    myTask.customvariable= customvariable;
    myTask.customvariabletwo= customvariabletwo;
    TaskManager.AddTask<myTask>(s => s.ToRunOnceAt(task.Time));
```
However, I found out that this is not valid.

**Comment by aijorgenson** [comment]
Found another way around it for my application, however this would be a very good feature.

**Comment by tallesl** [comment]
I'm putting this on "on hold" (for comments and opinions from others).

Increasing flexibility may also increase complexity (the more options you give less abstraction you do).

**Comment by frapid** [comment]
Please consider supporting 'JobId' which is super useful to identify jobs during schedules. We currently use another scheduler which supports this feature.

**Comment by tallesl** [comment]
@frapid 

You can assign a name to your schedule, does that work out for you?

```cs
// Assigning a name in your registry:
Schedule(() => { }).WithName("MySchedule");

// Getting the schedule somewhere else:
var mySchedule = JobManager.GetSchedule("MySchedule");
```

**Comment by frapid** [comment]
@tallesl, I am afraid, it won't work for us.

What we have is a multi-tenant web application which allows you to create a new tenant (website) when you visit the installation page-->"anydomain.com/install". The page would schedule the installation job with a key (or JobId) `anydomain.com`. When the installation job (`IJob`) is fired by the scheduler, we would want to know that the tenant to be created is `anydomain.com`.

**Comment by tallesl** [comment]
@frapid 

 I see. If I change the library to support the following would it work for you?

```cs
public class WebsiteJob : IJob
{
    public string Domain { get; set; }

    public void Execute()
    {
        // do something with the domain
    }
}

// somewhere in your running code
var job = new WebsiteJob { Domain = "anydomain.com" };
JobManager.AddJob(job, s => s.ToRunOnceAt(date));
```

**Comment by frapid** [comment]
@tallesl, this is perfect!

**Comment by tallesl** [comment]
Implemented on version 4.1.0.

Thank you for suggesting the feature guys :+1:

**Comment by frapid** [comment]
Amazing job, kudos to you @tallesl! This solution feels better than what I have been using on another library.

I am migrating Frapid to CoreCLR. I want to replace the existing task scheduler with FluentScheduler. What is the ETA of this feature to arrive in nuget package?

Thanks a million again!

**Comment by tallesl** [comment]
@frapid It's already on NuGet

**Comment by AlonAm** [comment]
Would be useful to be able to add parameters to a job AND use IoC
For example:

JobManager.AddJob<MyJob>(s => s.WithParameter("Param1", myParam).ToRunOnceAt(date));

**Comment by Enoinoo** [comment]
> ```cs
> public class WebsiteJob : IJob
> {
>     public string Domain { get; set; }
> 
>     public void Execute()
>     {
>         // do something with the domain
>     }
> }
> 
> // somewhere in your running code
> var job = new WebsiteJob { Domain = "anydomain.com" };
> JobManager.AddJob(job, s => s.ToRunOnceAt(date));
> ```

Is there a way to schedule a job like this through `Registry`?
