### ISSUE TITLE
Does this framework supports Owin?

### ISSUE THREAD

**Issue by HarelM** [fluentscheduler/FluentScheduler#66]
I can't find a proper answer using google whether IRegisteredObject is supported by Owin.
If it's not does this mean this framework will not work when hosting it on Owin?

**Comment by tallesl** [comment]
Hi there,

I'm not experienced with OWIN (never used actually), but from what I know it's a community standard interface between web applications and web servers (so web app developers aren't dependent on a specific web server such as IIS, right?).

If that's the case I don't know if the question even make sense, FluentScheduler isn't a web app.

**Comment by HarelM** [comment]
Please read the title of the question.
If this scheduler is able to run on an application that is hosted with OWIN it should adhere to OWIN lifecycle and memory management. Since a scheduler is something that should always be running, using it with a framework that initializes itself from time to time might be problematic. This is the case with both regular hosted asp.net apps and OWIN. I see that you are supporting asp.net and I wanted to know if you support OWIN as well.
BTW, 17 days to answer a question is more then enough time to find alternatives. Thanks anyway.

**Comment by tallesl** [comment]
I have not only read the title of your question but I also answered.

Now that if you explained further in a second comment I realize what you meant (explaining further in a second message... that's almost the definition of a "conversation", don't you agree?).

You mentioned that you "see that you are supporting asp.net", but you if read the README more carefully you'll realize that we don't. We are merely teaching (via snippet) how to use along with ASP.NET, the effort (that isn't much by the way) is on the consumer.

The problem with OWIN is the same with ASP.NET, we would have to rely on a dependency that others (probably most of the other users) don't use (see [#4](https://github.com/fluentscheduler/FluentScheduler/issues/4#issuecomment-10926795)).

I've been considering creating a FluentScheduler.Web or FluentScheduler.AspNet package. If you see value on doing that we could hook up a FluentScheduler.Owin as well. What do you think?

Any help is welcome, even if it's not a patch. Pointing out how FluentScheduler should "wire up" to OWIN is a great start (since I'm not experienced with it).

P.S.:

I noticed a rude tonality in your last message ("read the title", "x days is enough").
As for the late answer, I'm sorry about that, I was on vacation!

Open source is about helping each other. Chill out dude :wink:

**Comment by HarelM** [comment]
Sorry for the tone, it seemed like you dismissed my issue without really answering it...
I ended up writing a small exe file that the windows scheduler is running due to a lot of reading about scheduling in windows. The only problem that I have with that approach is that you need to configure the server and it's not just about publishing the code, but all the other stuff I tried just didn't work...
Good luck with this project! :-)

**Comment by tallesl** [comment]
Yeah, making a separated Windows Service is not as good. That's precisely the reason that I started using FluentScheduler.

Aren't you able to start/stop FluentScheduler manually according to OWIN lifecycle (just as the ASP.NET example on the README)?

**Comment by HarelM** [comment]
I couldn't figure out how to configure it on OWIN startup, that's why I opened this question 😁

**Comment by tallesl** [comment]
But now it's a FluentScheduler question or an OWIN question?

For FluentScheduler it's just a matter of starting/stopping the `TaskManager` by calling `Initialize`/`Stop` and listening for a stop on the tasks ([just like the example on README](https://github.com/fluentscheduler/FluentScheduler#using-it-with-aspnet)).

As for OWIN, again, I don't have experience with it. [Their documentation didn't helped much](https://github.com/owin/owin/blob/master/owin.md#4-application-startup), but searching a little bit more I found [this](http://www.asp.net/aspnet/overview/owin-and-katana/owin-startup-class-detection) for starting up and [this](http://stackoverflow.com/q/23317965/1316620) for shutting down. Maybe that's what you need.

Ah, and if you manage to make it work please let me know, so we can put an example on README just like the ASP.NET one.

**Comment by HarelM** [comment]
My experience with OWIN is limited as well...
Well the question is about how to combine them both since I can't make the OWIN hosted server live forever (I can in theory but it is bad practice as far as I understand).
Ok, let me see if I can translate the the Asp.Net theory to OWIN:
Asp.Net does not have the event OWIN has and thus in order to know if the server is shutting down you need to implement the ```IRegisteredObject``` so that you'll get a "Stop" callback when it does.
In OWIN you can hook to an event and basically do the same.
Assuming that the above is right the only questions I have are 
1. If I should create a ```TaskManager``` every startup of the server (I think I know that this is needed).
2. When creating this manager will the missing scheduled tasks that might have been missed since the last time the manager was up will run? If so, how does the scheduler knows which tasks were missed since I don't implement any storage...

The last part of question 2 is crucial since without it I can't really relay on this scheduling especially if my tasks are running every two days.

**Comment by tallesl** [comment]
Your assumptions seems to be right.

1. Yes. If on every shutdown the TaskManager goes down, on every startup you should initialize again.
2. Yes, there's no storage, it forgets everything once your restart it.

Setting up some sort of storage would solve your problem, but would not only require a great amount of effort to adapt the library but also would increase the complexity (file or database? user? password? permissions? cleaning up old data?). Going from no IO to yes IO is a big deal.

If you are running every two days there's a way to get around your problem. You could create a configuration flag on your `.config` (`<appSettings>`) saying if it should start counting due today or due tomorrow. Not the most elegant solution (you got to remember this when deploying/restarting) but still...

**Comment by HarelM** [comment]
I think you don't have to implement any thing but let the developer who uses this framework implement what's needed.
you can define an interface called ```ITaskStorage``` and allow the developer to set a property of the ```TaskManager``` or as an optional constructor argument etc...
the ```ITaskStorage``` will be defined by methods like ```GetLastRun(int taskId)```and ```SetRunTime(int taskId, DateTime time)``` (can be string instead of int) this way you can check if this interface was set and if so whenever a task runs you'll call the methods in the interface. 
Sounds too complicated?
The above implementation does not require your framework to know how the storage is kept - either file system or database - for you it's the same...

**Comment by tallesl** [comment]
I guess we just changed the topic now. I've created [another issue](https://github.com/fluentscheduler/FluentScheduler/issues/68) for discussing your last suggestion.

As for the OWIN, the favor I asked before still remains: if you manage to put it work please let me know so I can but an example on README to help others :wink:
