### ISSUE TITLE
migration issue

### ISSUE THREAD

**Issue by vinodkumar1080** [fluentscheduler/FluentScheduler#70]
PortableLibrary\PortableLibrary.csproj: The project 'PortableLibrary.csproj' was created with a newer version of Visual Studio which is incompatible with your version.The  project opens
![migration report](https://cloud.githubusercontent.com/assets/15869922/13598482/fc08e24e-e543-11e5-871b-bd0e4425de01.png)
 with newer versions of Visual Studio not supported for all versions .Please add sample which should support lower version .In current uploaded sample PortableLibrary build with framework version 5.0 so i cant downgrade your project.To understand completely and incorporate with mvc application i need a sample with lower version.

**Comment by tallesl** [comment]
There's no problem with that, the main project ("Library") still runs fine (I tested on VS 2013).

By the way, to use FluentScheduler in a application of yours, consider using the [NuGet package](https://www.nuget.org/packages/FluentScheduler).
