### ISSUE TITLE
Question about different behavior from 3.1.46 to Current Master

### ISSUE THREAD

**Issue by jplindgren** [fluentscheduler/FluentScheduler#73]
Hi guys, sorry about my english. I noticed a different behavior in resolving dependencies with a custom ITaskFactory from version 3.1.46 to Master branch.
In 3.1.46 the GetInstance method from my custom TaskFactory was called everytime my job was fired, the opposite of Master branch in which my GetInstance is being called only once at the schedule of the job.
Is it a desided behavior? Or it will be changed in next versions?

Actually this behavior help me in registering jobs for diferent tenants in my application.
In Master Branch i can do something like that and it works.
```
var tenants = new string[] { "tenant1", "tenant2", "tenant3" };
TimeSpan delayBetweenTenants = TimeSpan.FromMinutes(1);
foreach (var tenant in tenants) {
       var tenantContainer = CreateSpecificContainerForTenant(container, tenant);

        JobManager.TaskFactory = new MyJobFactory(tenantContainer);
        JobManager.Initialize(new MyRegistry(delayBetweenTenants));                
 }
```

Thank you in advance.

**Comment by tallesl** [comment]
That shouldn't change. I'm checking it (and changing it back) when I got some time...

Thx for reporting it :+1:

**Comment by tallesl** [comment]
Thankfully it's was only on the current master, 4.0.0 is fine.

I found the culprit (f0d03a6) and reverted it, was totally my fault.
