### ISSUE TITLE
Tasks seems to run on creation schedule

### ISSUE THREAD

**Issue by ismijgelijk** [fluentscheduler/FluentScheduler#74]
I have a class that very much looks like this:

```
    public class MyRegistry : Registry
    {
        public MyRegistry ()
        {
            var schedule = Schedule<MyTask>();
            var timeSpan = Settings.MyTaskTimeOfDay;
            var runOnceOnStartup = Settings.MyTaskRunOnceOnStartup;
            if (runOnceOnStartup)
            {
                schedule.ToRunNow();
                Settings.MyTaskRunOnceOnStartup= false;
            }
            var nextRun = DateTime.Now.Date.Add(timeSpan);
            schedule.ToRunOnceAt(nextRun).AndEvery(1).Days();
        }
    }
```

For some reason my task gets scheduled to run immediately, regardless of wether the runOnceOnStartup-flag is set.
Am I using the scheduling incorrectly?
Or is this indeed a bug?

**Comment by tallesl** [comment]
It seems that you're using it wrong, maybe the feedback bellow helps you.
I'm closing the issue but feel free to ask to reopen it.

**First remark**

If you change the configuration on the same schedule instance it overrides your previous configuration.

```cs
var scheduler = Schedule<MyTask>();
schedule.ToRunNow();
schedule.ToRunOnceAt(nextRun).AndEvery(1).Days(); // overrides the scheduling above
```

To do both simply instantiate two of them:

```cs
var schedule1 = Schedule<MyTask>();
schedule1.ToRunNow();

var schedule2 = Schedule<MyTask>();
schedule2.ToRunOnceAt(nextRun).AndEvery(1).Days();
```

Embracing the *fluent* spirit, I suggest you to not store the schedule in variable:

```cs
Schedule<MyTask>().ToRunNow();
Schedule<MyTask>().ToRunOnceAt(nextRun).AndEvery(1).Days();
```

**Second remark**

If your `nextRun` variable below end up having a date that is earlier than "now" the scheduler runs it immediately:

```cs
var nextRun = DateTime.Now.Date.Add(timeSpan);
schedule.ToRunOnceAt(nextRun).AndEvery(1).Days();
```

**Comment by ismijgelijk** [comment]
Perfect, thank you
I think your second remark is what caused me to rewrite the code in the way I posted it here
