### ISSUE TITLE
run a task on the last day on a month at mid night (00,00)

### ISSUE THREAD

**Issue by babinbabu** [fluentscheduler/FluentScheduler#75]
I need to run my task with this conditions:
1) run a task on the last day on a month at mid night (00,00) time zone UTC+08:00

**Comment by tallesl** [comment]
```cs
class MyRegistry : FluentScheduler.Registry
{
    Schedule(() => System.Console.WriteLine("Today is the last day of the month!")).ToRunEvery(1).Months().OnTheLastDay();
}
```

**Comment by babinbabu** [comment]
Hi,

Can I Run this at time zone UTC+08:00

**Comment by tallesl** [comment]
Well... you can't configure it on the library.

You can either rely on the machine date (no change) or scheduling property according to utc (`UseUtcTime()`). If you're afraid about the machine date the best is to rely on UTC.

**Comment by babinbabu** [comment]
Ok,

Can I Use 

class MyRegistry : FluentScheduler.Registry
{
    Schedule(() => System.Console.WriteLine("A new month is about to start!")).ToRunEvery(0).Months().On(1);
}
 instead  of 

class MyRegistry : FluentScheduler.Registry
{
    Schedule(() => System.Console.WriteLine("A new month is about to start!")).ToRunEvery(1).Months().OnTheLastDay().At(23, 59);
}

**Comment by babinbabu** [comment]
Ok,

Can I Use

class MyRegistry : FluentScheduler.Registry
{
Schedule(() => System.Console.WriteLine("A new month is about to start!")).ToRunEvery(0).Months().On(1);
}
instead of

class MyRegistry : FluentScheduler.Registry
{
Schedule(() => System.Console.WriteLine("A new month is about to start!")).ToRunEvery(1).Months().OnTheLastDay().At(23, 59);
}
