### ISSUE TITLE
Save Scheduled Jobs

### ISSUE THREAD

**Issue by captkirk88** [fluentscheduler/FluentScheduler#78]
Add the ability to persist scheduled jobs to disk for reloading when the program closes.  This way they don't need to be hard coded all of the time.

The Scheduler class could easily be configured to save in a JSON format or similar readable format to edit jobs too.

**Comment by captkirk88** [comment]
On second thought, I have no idea how you could persist a Job that uses a Action or lambda since those are not serializable by default.

Might be a little harder to do..

**Comment by tallesl** [comment]
(If I understood you correctly)

Don't get me wrong but serializing the actual job implementation seems like a nightmare. Not only for the trouble of implementing it but also imagine the confusion on the developer head on figuring out which one is gonna run, the one serialized saved somewhere or the fresh one in the code?

An idea that may serve you is to store the last run date of the schedules so the library wouldn't "forget" the last schedule run (see #68).

I'm closing this one but feel free to ask for reopening.
