### ISSUE TITLE
While debugging and doing F10 it shows "jobmanager.cs not found"

### ISSUE THREAD

**Issue by saggaraman** [fluentscheduler/FluentScheduler#81]
While debugging the code which is run through Fluent Scheduler, on press of F10, VS 2013 gives out a debug windows stating "jobmanager.cs not found"

**Comment by tallesl** [comment]
Are you running the FluentScheduler project itself or a project that uses it as a library?

For the former it seems a really odd message to appear, as for the latter I don't see the problem at all.

More information on it can help.

**Comment by saggaraman** [comment]
I have class Library named "Bootstrap", which has all Fluent Scheduler implementation.  Actual implementation is another Class library.
I am calling the "Bootstrap" from Console Application for now.

Hope this help. Do let me know if any other information is required

**Comment by tallesl** [comment]
OK but what's the problem?

Visual Studio need a source file to debug the library, that's what it's asking.

Do you want to debug FluentScheduler?
Then clone this repository and point Visual Studio to the file.

Maybe you don't want to debug it?
Just don't step into it then.

I'm closing this issue (but feel free to further comment on it).

**Comment by tallesl** [comment]
But what's is the problem?

Do you want to debug FluentScheduler?
Then clone this repository and point Visual Studio to the file.

Maybe you don't want to debug it?
Don't step into it with the debugger then.

I'm closing this issue (feel free to comment on it though).
