### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by mrahhal** [fluentscheduler/FluentScheduler#83]
Plans to support .NET Core anytime soon?

**Comment by tallesl** [comment]
It already does, from version [4.0.0](https://github.com/fluentscheduler/FluentScheduler/releases/tag/4.0.0) upwards.
I'm closing this issue, but if you have any trouble using the library with .NET Core just ask to reopen.

**Comment by mrahhal** [comment]
Oh, didn't notice the `project.json` was with the PCL. No problems, thanks!

**Comment by uflex99** [comment]
Can you please provide an example for ASP.NET CORE. The current one is making use of IRegisterObject interface for gracefully start- and stopping but the HostingEnvironment library is no longer there.

**Comment by uflex99** [comment]
Can you please provide an example for ASP.NET CORE. The current one is making use of IRegisterObject interface for gracefully start- and stopping but the HostingEnvironment library is no longer there.

**Comment by tallesl** [comment]
@uflex99 

Right now I have no solution for it (#94).
