### ISSUE TITLE
FluentScheduler in azure

### ISSUE THREAD

**Issue by babinbabu** [fluentscheduler/FluentScheduler#85]
FluentScheduler is getting error 

Locating source for 'C:\Users\Talles\GitHub\FluentScheduler\Library\JobManager.cs'. Checksum: SHA1 {b9 3d 2b 34 f1 dc d4 92 50 3b 30 df 3 9 c5 7b 1c 9f 35 a7}
The file 'C:\Users\Talles\GitHub\FluentScheduler\Library\JobManager.cs' does not exist.
Looking in script documents for 'C:\Users\Talles\GitHub\FluentScheduler\Library\JobManager.cs'...
Looking in the projects for 'C:\Users\Talles\GitHub\FluentScheduler\Library\JobManager.cs'.
The file was not found in a project.
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\crt\src\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\crt\src\vccorlib\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\atlmfc\src\mfc\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\atlmfc\src\atl\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\atlmfc\include'...
The debug source files settings for the active solution indicate that the debugger will not ask the user to find the file: C:\Users\Talles\GitHub\FluentScheduler\Library\JobManager.cs.
The debugger could not locate the source file 'C:\Users\Talles\GitHub\FluentScheduler\Library\JobManager.cs'. 

How to fix this issue ?

**Comment by tallesl** [comment]
What exactly you were doing? This doesn't tell much.

**Comment by babinbabu** [comment]
My code in Global.asax

JobManager.JobException += JobExceptionHandler;
JobManager.Initialize(new NotificationScheduler());
           
        static void JobExceptionHandler(FluentScheduler.JobExceptionInfo info, FluentScheduler.UnhandledExceptionEventArgs e)
        {
            log.Error("An error happened with a scheduled job: " + e.ExceptionObject);
        }


NotificationScheduler.cs page

 public NotificationScheduler()
        {
            UseUtcTime();
            Schedule<MyTest>().ToRunEvery(2).Minutes();
       }

 class MyTest : IJob
        {
            public void Execute()
            {
                Testing();
            }
        }

 public static void Testing()
        {
            log.Error("Mytesting Success" + DateTime.UtcNow);
        }


its working fine in my local but getting the error that mentioned in my last comment. but nothing happening in while publishing in azure.

**Comment by tallesl** [comment]
The first post of your doesn't contain the error, just a note stating that couldn't find FluentScheduler source code to further debug (that's normal).

Can you get the exception that happened?

**Comment by babinbabu** [comment]
No error getting, but FluentScheduler is not working because i have given that append some text to error log, but that also not working.

**Comment by tallesl** [comment]
Without an exception message and stack trace it's hard to find out what's the problem...

I'm closing this one since there's another open issue (#80) stating this yet to be found problem with azure.
