### ISSUE TITLE
Crash when first job is executed yearly

### ISSUE THREAD

**Issue by Wautvda** [fluentscheduler/FluentScheduler#87]
I have a job that has the folowing schedule: 
`schedule.ToRunEvery(1).Years().On(1).At(0, 0)`
When executing the following code 
`JobManager.AddJob(currentTask.Execute, schedule)` (not code has been altered to focus on the problem), I get the following exception: 

> Time-out interval must be less than 2^32-2.\r\nParameter name: dueTime
>    at System.Threading.Timer.Change(Int64 dueTime, Int64 period)
>    at System.Threading.Timer.Change(TimeSpan dueTime, TimeSpan period)
>    at FluentScheduler.JobManager.ScheduleJobs() in C:\Users\Talles\GitHub\FluentScheduler\Library\JobManager.cs:line 408
>    at FluentScheduler.JobManager.AddJob(Action`1 jobSchedule, Schedule schedule) in C:\Users\Talles\GitHub\FluentScheduler\Library\JobManager.cs:line 294
>    at FluentScheduler.JobManager.AddJob(Action job, Action`1 schedule) in C:\Users\Talles\GitHub\FluentScheduler\Library\JobManager.cs:line 256
>    at Aucxis.VAUC.DataCore.Plugin.TaskScheduler.TaskLoader.ScheduleTask(ITaskProcessor currentTask, String scheduleTime) in D:\Development\UniverseleRegelaar\DataCore\Plugins\Aucxis.VAUC.DataCore.Plugin.TaskScheduler\TaskLoader.cs:line 132

When I debug i find that the timerInterval (in JobManager.cs) has an interval of 171 days which is more then the maximum interval. Is there any way to catch this exception?

A solution could be adapting the folowing code from

> var timerInterval = firstJob.NextRun - Now;
>             if (timerInterval <= TimeSpan.Zero)
>             {
>                 ScheduleJobs();
>                 return;
>             }
> 
>             _timer.Change(timerInterval, timerInterval);

To

> var timerInterval = firstJob.NextRun - Now;
>             if (timerInterval <= TimeSpan.Zero)
>             {
>                 ScheduleJobs();
>                 return;
>             }
>             if (timerInterval.Ticks >= MaxValue)
>                 _timer.Change(new TimeSpan(1, 0, 0, 0), new TimeSpan(1, 0, 0, 0));
>             else
>                 _timer.Change(timerInterval, timerInterval);

that way it checks daily and adapts the interval

**Comment by tallesl** [comment]
Fixed on [5.0.0](https://github.com/fluentscheduler/FluentScheduler/releases/tag/5.0.0).
