### ISSUE TITLE
When scheduling weekly for current day of week it does not execute

### ISSUE THREAD

**Issue by johnwpowell** [fluentscheduler/FluentScheduler#90]
For this example, consider it is Tuesday 9:30am.
Create a schedule to run Weekly on Tuesdays at 10:00am.
The next scheduled time is the following Tuesday at 10am.  It should be this Tuesday at 10:00am.

Noticed that in this scenario when scheduling for Wednesday of this week, it scheduled it for Wednesday of next week--so its more than just the current day.

**Comment by tallesl** [comment]
How are you calling it?

If you call `Weeks(1)` the library makes sure that at least one week has passed (next Tuesday). Now if you call `Weeks(0)` it doesn't matter if it's a little less than seven days or even in the same day (this Tuesday). This behavior goes back to issue #1.

Calling `Weeks(0)` is completely counter-intuitive, `Week()` (without parameter) would be better off. I'm marking this as a feature change.

**Comment by johnwpowell** [comment]
I was calling it using Weeks(1) but figured out it needed to be Weeks(0).

**Comment by tallesl** [comment]
Since using zero is counter-intuitive I added a [note explaning it on README](https://github.com/fluentscheduler/FluentScheduler#running-jobs-weekly).
