### ISSUE TITLE
JobManager.JobException dependency injection

### ISSUE THREAD

**Issue by MrGold** [fluentscheduler/FluentScheduler#91]
Hello,

To log job exceptions I've written following lines;

```
JobManager.JobException += JobManager_JobException;
private static void JobManager_JobException(JobExceptionInfo obj)
{
            ILogger logger = EngineContext.Current.Resolve<ILogger>();
            logger.Error(obj.Exception);
}
```

It is working but i cannot inject ILogger here.I have to use service locator which i prefer to avoid.
Is there any other way in FluentScheduler that i can inject  dependencies and use them in JobException event? 

Thanks,

**Comment by tallesl** [comment]
Nope. You have to keep doing like that.

There are two distinct schools on designing an API:

* One is the "enterprise" way, the library would be very opinionated on how you talk to it, demanding that you implement specific interfaces and having a say on the designing of your own code base.
* The other is being more "lightweight", using simple unopinionated techniques for talking to your code, like a simple event field, leaving the actual design of your code base entirely on your shoulders.

You can see the first as a "framework" and the latter more as a "library". [I'm on the library side](https://github.com/fluentscheduler/FluentScheduler/issues/71).

I'm closing this issue but feel free to comment further on it.
