### ISSUE TITLE
How use with ASP.NET Core 1.0.0

### ISSUE THREAD

**Issue by KANekT** [fluentscheduler/FluentScheduler#92]
How to use this FluentScheduler in Microsoft.AspNetCore.Mvc (ASP.NET Core 1.0.0)?

**Comment by tallesl** [comment]
Add the dependency to your `project.json` file, like:

```json
  "dependencies": {
    "FluentScheduler": "5.0.0"
  }
```

Then `dotnet restore` and you're good to go, just use any of the examples on README.
