### ISSUE TITLE
Blocking schedules on stop

### ISSUE THREAD

**Issue by tallesl** [fluentscheduler/FluentScheduler#93]
The current `JobManager.Stop` just stops the library main timer but it doesn't block the currently running schedules.

A `JobManager.StopAndBlock` would be nice.

**Comment by mdissel** [comment]
Any progress? I'm currently using a static variable to detect a Stop (of my windows service) and stop the activities of the current active job.

**Comment by tallesl** [comment]
@mdissel

Sorry, no progress so far. But this is the easiest to implement of all open issues, I believe that in the next week or so I have it done.

**Comment by skorunka** [comment]
+1

**Comment by tallesl** [comment]
> I believe that in the next week or so I have it done.

What a lie. Sorry for taking so long guys...

I just finished the implementation (was really simple after all).
I still have to finish a pull request here and an issue there, but as soon I have it published on NuGet I let you know here.

**Comment by tallesl** [comment]
Published on version 5.1.0.

**Comment by AlbertoCe** [comment]
Great ! Thank you !

**Comment by nield** [comment]
Hi, would it be possible to add a timeout parameter? When timeout is reached the scheduler stops.

I used StopAndBlock(), but due to a database connection error, I could not stop my windows service.

Thanks for an awesome library 👍
