### ISSUE TITLE
ASP.NET Core support

### ISSUE THREAD

**Issue by tallesl** [fluentscheduler/FluentScheduler#94]
While the library supports [.NET Core](https://github.com/fluentscheduler/FluentScheduler#using-it-with-net-core), it's not already clear what would be needed to support running it with ASP.NET Core.

You can find out when ASP.NET Core is shutting down with the following `Startup.cs` (adapted [Getting Started](https://docs.asp.net/en/latest/getting-started.html)):

``` cs
using System;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace aspnetcoreapp
{
    public class Startup
    {
        public void Configure(IApplicationBuilder app, IApplicationLifetime lifetime) // added the IApplicationLifetime parameter
        {
            app.Run(context =>
            {
                return context.Response.WriteAsync("Hello from ASP.NET Core!");
            });
            lifetime.ApplicationStopping.Register(() => Console.WriteLine("Bye from ASP.NET Core!")); // added this line
        }
    }
}
```

But then there's <del>two problems</del> one problem:
- Just calling `JobManager.Stop` wouldn't be enough since [the current implementation doesn't block the running tasks](https://github.com/fluentscheduler/FluentScheduler/issues/93) (that's a problem not just for ASP.NET Core by the way);
- <del>It's unclear if shutting down due to idleness plays a role on ASP.NET Core</del> ([looks like that's not a problem](https://github.com/aspnet/Home/issues/1429#issuecomment-238110277)).

**Comment by jpsingleton** [comment]
I'm not sure if this is exactly what you're having problems with but as I wrote about this as [part](https://www.packtpub.com/mapt/book/Application%20Development/9781785881893/3/ch03lvl1sec18/Asynchronous%20operations) of my recent [book](https://unop.uk/book/) I thought I'd chip in.

You can do a blocking shutdown to approximate what `HostingEnvironment.QueueBackgroundWorkItem` (QBWI) does in the full .NET Framework (>= 4.5.2). You can get the `ApplicationStopping` cancellation token from `lifetime` (as in your example above) and wait on that. There is also an `ApplicationStopped` token than hooks in slightly later in the life-cycle.

The [docs](https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/AspNetCore/Hosting/IApplicationLifetime/) say that for both; "Shutdown will block until this event completes."

**Comment by tallesl** [comment]
@jpsingleton 

Thank you very much for your input, that's precisely what I needed to know!

**Comment by raupes** [comment]
Hi, any improvements for hosting in asp.net core so far?

**Comment by tallesl** [comment]
Published a `JobManager.StopAndBlock` method on version 5.1.0.

**Comment by KANekT** [comment]
Add please documentation for use

**Comment by jpsingleton** [comment]
Thanks! I've updated [ANCLAFS.com](https://anclafs.com/) (https://github.com/jpsingleton/ANCLAFS/commit/f54b6a7eec6f300a6f1bce255279f5f56aec80c6).

**Comment by itavero** [comment]
@tallesl When will the README be updated?
