### ISSUE TITLE
Unity DI

### ISSUE THREAD

**Issue by javenosa** [fluentscheduler/FluentScheduler#95]
Hello,

I was trying to implement the library with DI over Unity, but I cannot get it done.
Here is my code. Actually the DI works fantastic over my entire project, the problem is only over the Job.

    public class EmailJob : IJob, IRegisteredObject
    {
        [Dependency]
        public IService Service { get; set; }

        private readonly object _lock = new object();

        private bool _shuttingDown;

        public EmailJob()
        {
            HostingEnvironment.RegisterObject(this);
            // Service is null
        }

        public void Execute()
        {
            lock (_lock)
            {
                if (_shuttingDown)
                    return;
				

				Service.list(); // <- Service is null
            }
        }

        public void Stop(bool immediate)
        {
            lock (_lock)
            {
                _shuttingDown = true;
            }

            HostingEnvironment.UnregisterObject(this);
        }
    }
	
	
    public class MyRegistry : Registry
    {
        public MyRegistry()
        {
            Schedule<EmailJob>().ToRunNow().AndEvery(2).Seconds();
        }
    }

    public class UnityJobFactory : IJobFactory
    {
        private readonly IUnityContainer _container;

        public UnityJobFactory(IUnityContainer container)
        {
            _container = container;
        }

        public IJob GetJobInstance<T>() where T : IJob
        {
            return _container.Resolve<T>();
        }
    }

	Application_Start()
	{
		JobManager.JobFactory = new UnityJobFactory(container);
		JobManager.Initialize(new MyRegistry());
	}	

    Exception occurred while: while resolving.
    Exception is: NullReferenceException

Can you provide an example code?

Thanks,
Javenosa

**Comment by tallesl** [comment]
Have you registered `EmailJob` on your Unity container?

I'm unfamiliar with the `[Dependency]` attribute, but below is a working example that uses `UnityContainer.RegisterType`.

```cs
using FluentScheduler;
using Microsoft.Practices.Unity;
using System;
using System.Threading;

public class SomeJob : IJob
{
    public void Execute()
    {
        Console.WriteLine("Some job.");
    }
}

public interface IClearJob : IJob { }

public class ClearJob : IClearJob, IJob
{
    public void Execute()
    {
        Console.Clear();
    }
}

public class JobFactory : IJobFactory
{
    private readonly IUnityContainer _container = new UnityContainer();

    public JobFactory()
    {
        _container.RegisterType<IClearJob, ClearJob>();
        _container.RegisterType<IJob, SomeJob>();
    }

    public IJob GetJobInstance<T>() where T : IJob
    {
        return _container.Resolve<T>();
    }
}

public class Program
{
    public static void Main(string[] args)
    {
        var registry = new Registry();

        registry.Schedule<IJob>().ToRunEvery(1).Seconds();
        registry.Schedule<IClearJob>().ToRunEvery(5).Seconds();

        JobManager.JobFactory = new JobFactory();
        JobManager.Initialize(registry);

        Thread.Sleep(Timeout.Infinite);
    }
}
```

**Comment by javenosa** [comment]
tallesl, 

Thanks for your response.

Your code doesn't use any service over the Job, just use Unity. 

I forgot to add the RegisterType as you say but in any case, the code doesn't work.

My JobFactory has one parameter over the constructor "container", that is the actual container used over the entire ASP.NET MVC site and works ok.

Here is my updated JobFactory:

    public class UnityJobFactory : IJobFactory
    {
        private readonly IUnityContainer _container;

        public UnityJobFactory(IUnityContainer container)
        {
            _container = container;
            _container.RegisterType<IJob, EmailJob>();
        }

        public IJob GetJobInstance<T>() where T : IJob
        {
            return _container.Resolve<T>();
        }
    }

The error happen when it try to resolve the service on the Job implementation.
Any idea?

Thanks,
Javenosa

**Comment by javenosa** [comment]
Tallesl,

Can you provide any idea/fix about this issue??

Thanks!

**Comment by tallesl** [comment]
Without an exception message and a stack trace is hard to help you out.

But to be honest, looks like you're having problems with Unity (and not FluentScheduler). If that's the case it's better to ask the Unity folks...

**Comment by Thanood** [comment]
I don't have any Unity experience but a with DI containers in general.

My guess is that Unity doesn't decorate `IJob` instances because it doesn't instantiate/manage them. Jobs are created by `JobFactory` using `Activator.CreateInstance<T>();` here: https://github.com/fluentscheduler/FluentScheduler/blob/master/Library/JobFactory.cs#L25

AFAIK the container doesn't get a chance to intercept this.
But if Unity actually *can* do that, that would be the place to look, I guess. :smile:
