### ISSUE TITLE
Get Next execution datetime after scheduling

### ISSUE THREAD

**Issue by alberthoekstra** [fluentscheduler/FluentScheduler#98]
Hello,

I've got a couple off jobs and I schedule them.
To check if they are scheduled correctly I want to know when the next execution time will be.

I can't find this information.
Can you help me find it?

**Comment by tallesl** [comment]
Hi,

There's a `NextRun` property in the `Schedule` class that does exactly that.

You can access the schedule object by getting it by name (if you assigned any)  with `JobManager.GetSchedule(name)` or by storing the object right after its creation on your registry.
You can also try to find it on `JobManager.RunningSchedules` or `JobManager.AllSchedules`, 

I hope it helps. I'm closing this issue but feel free to comment it further.
